class V099B1StrengthExpectedExercise {
  const V099B1StrengthExpectedExercise({
    required this.key,
    required this.group,
    required this.equipmentCue,
    required this.equipmentKey,
  });

  final String key;
  final String group;
  final String equipmentCue;
  final String equipmentKey;
}

const v099b1StrengthExpectedExercises = <V099B1StrengthExpectedExercise>[
  V099B1StrengthExpectedExercise(
    key: 'supino_reto_com_barra',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_reto_com_barra_controlado',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_reto_com_barra_com_pausa',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_reto_com_barra_em_tempo_lento',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_declinado_com_barra_controlado',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_inclinado_com_barra_controlado',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_inclinado_com_barra_com_pausa',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'supino_inclinado_com_barra_em_tempo_lento',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_a_frente',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_a_frente_controlado',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_a_frente_com_pausa',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_a_frente_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_com_pegada_neutra',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_com_pegada_neutra_controlado',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_com_pegada_neutra_com_pausa',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'puxada_alta_com_pegada_neutra_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Lat pulldown',
    equipmentKey: 'lat_pulldown',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_sentada_no_cabo',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_sentada_no_cabo_controlado',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_sentada_no_cabo_com_pausa',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_sentada_no_cabo_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_baixa_unilateral',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_baixa_unilateral_controlado',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_baixa_unilateral_com_pausa',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'remada_baixa_unilateral_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_de_ombro_com_halteres',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_de_ombro_com_halteres_controlado',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_de_ombro_com_halteres_com_pausa',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_de_ombro_com_halteres_em_tempo_lento',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_na_smith_machine',
    group: 'Ombros',
    equipmentCue: 'Smith',
    equipmentKey: 'smith_machine',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_na_smith_machine_controlado',
    group: 'Ombros',
    equipmentCue: 'Smith',
    equipmentKey: 'smith_machine',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_na_smith_machine_com_pausa',
    group: 'Ombros',
    equipmentCue: 'Smith',
    equipmentKey: 'smith_machine',
  ),
  V099B1StrengthExpectedExercise(
    key: 'press_na_smith_machine_em_tempo_lento',
    group: 'Ombros',
    equipmentCue: 'Smith',
    equipmentKey: 'smith_machine',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_45_graus',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_45_graus_controlado',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_45_graus_com_pausa',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_45_graus_em_tempo_lento',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_horizontal',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_horizontal_controlado',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_horizontal_com_pausa',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_press_horizontal_em_tempo_lento',
    group: 'Quadriceps',
    equipmentCue: 'Leg press',
    equipmentKey: 'leg_press',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_na_maquina',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_na_maquina_controlado',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_na_maquina_com_pausa',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_na_maquina_em_tempo_lento',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_unilateral',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_unilateral_controlado',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_unilateral_com_pausa',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'extensao_de_pernas_unilateral_em_tempo_lento',
    group: 'Quadriceps',
    equipmentCue: 'Extensao',
    equipmentKey: 'leg_extension',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_sentado',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_sentado_controlado',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_sentado_com_pausa',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_sentado_em_tempo_lento',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_deitado',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_deitado_controlado',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_deitado_com_pausa',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'leg_curl_deitado_em_tempo_lento',
    group: 'Isquiotibiais',
    equipmentCue: 'Leg curl',
    equipmentKey: 'leg_curl',
  ),
  V099B1StrengthExpectedExercise(
    key: 'ab_wheel_a_partir_dos_joelhos',
    group: 'Core',
    equipmentCue: 'Ab wheel',
    equipmentKey: 'ab_wheel',
  ),
  V099B1StrengthExpectedExercise(
    key: 'ab_wheel_a_partir_dos_joelhos_regressivo',
    group: 'Core',
    equipmentCue: 'Ab wheel',
    equipmentKey: 'ab_wheel',
  ),
  V099B1StrengthExpectedExercise(
    key: 'ab_wheel_a_partir_dos_joelhos_com_pausa_curta',
    group: 'Core',
    equipmentCue: 'Ab wheel',
    equipmentKey: 'ab_wheel',
  ),
  V099B1StrengthExpectedExercise(
    key: 'ab_wheel_a_partir_dos_joelhos_em_ritmo_lento',
    group: 'Core',
    equipmentCue: 'Ab wheel',
    equipmentKey: 'ab_wheel',
  ),
  V099B1StrengthExpectedExercise(
    key: 'farmer_walk_com_halteres',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'farmer_walk_com_halteres_regressivo',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'farmer_walk_com_halteres_com_pausa_curta',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B1StrengthExpectedExercise(
    key: 'farmer_walk_com_halteres_em_ritmo_lento',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
];
