class V099B2StrengthExpectedExercise {
  const V099B2StrengthExpectedExercise({
    required this.key,
    required this.group,
    required this.equipmentCue,
    required this.equipmentKey,
  });

  final String key;
  final String group;
  final String equipmentCue;
  final String equipmentKey;
}

const v099b2StrengthExpectedExercises = <V099B2StrengthExpectedExercise>[
  V099B2StrengthExpectedExercise(
    key: 'supino_declinado_com_barra_com_pausa',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_declinado_com_barra_em_tempo_lento',
    group: 'Peito',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_reto_com_halteres',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_reto_com_halteres_controlado',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_reto_com_halteres_com_pausa',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_reto_com_halteres_em_tempo_lento',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_inclinado_com_halteres_controlado',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_inclinado_com_halteres_com_pausa',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'supino_inclinado_com_halteres_em_tempo_lento',
    group: 'Peito',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_curvada_com_barra',
    group: 'Costas',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_curvada_com_barra_controlado',
    group: 'Costas',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_curvada_com_barra_com_pausa',
    group: 'Costas',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_curvada_com_barra_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_unilateral_com_halter',
    group: 'Costas',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_unilateral_com_halter_controlado',
    group: 'Costas',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_unilateral_com_halter_com_pausa',
    group: 'Costas',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'remada_unilateral_com_halter_em_tempo_lento',
    group: 'Costas',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_militar_com_barra_controlado',
    group: 'Ombros',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_militar_com_barra_com_pausa',
    group: 'Ombros',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_militar_com_barra_em_tempo_lento',
    group: 'Ombros',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_arnold',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_arnold_controlado',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_arnold_com_pausa',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'press_arnold_em_tempo_lento',
    group: 'Ombros',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_biceps_com_barra',
    group: 'Bíceps',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_biceps_com_barra_controlado',
    group: 'Bíceps',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_biceps_com_barra_com_pausa',
    group: 'Bíceps',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_biceps_com_barra_em_tempo_lento',
    group: 'Bíceps',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_alternado_com_halteres',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_alternado_com_halteres_controlado',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_alternado_com_halteres_com_pausa',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_alternado_com_halteres_em_tempo_lento',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_martelo_controlado',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_martelo_com_pausa',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_martelo_em_tempo_lento',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_inclinado_no_banco',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_inclinado_no_banco_controlado',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_inclinado_no_banco_com_pausa',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'curl_inclinado_no_banco_em_tempo_lento',
    group: 'Bíceps',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'suitcase_carry_unilateral',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'suitcase_carry_unilateral_regressivo',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'suitcase_carry_unilateral_com_pausa_curta',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'suitcase_carry_unilateral_em_ritmo_lento',
    group: 'Antebraco e pegada',
    equipmentCue: 'Halteres',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_hang_na_barra',
    group: 'Antebraco e pegada',
    equipmentCue: 'Barra',
    equipmentKey: 'pullup_bar',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_hang_na_barra_regressivo',
    group: 'Antebraco e pegada',
    equipmentCue: 'Barra',
    equipmentKey: 'pullup_bar',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_hang_na_barra_com_pausa_curta',
    group: 'Antebraco e pegada',
    equipmentCue: 'Barra',
    equipmentKey: 'pullup_bar',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_hang_na_barra_em_ritmo_lento',
    group: 'Antebraco e pegada',
    equipmentCue: 'Barra',
    equipmentKey: 'pullup_bar',
  ),
  V099B2StrengthExpectedExercise(
    key: 'pallof_press_no_cabo_regressivo',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'pallof_press_no_cabo_com_pausa_curta',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'pallof_press_no_cabo_em_ritmo_lento',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_alto',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'high_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_alto_regressivo',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'high_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_alto_com_pausa_curta',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'high_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_alto_em_ritmo_lento',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'high_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_baixo',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_baixo_regressivo',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_baixo_com_pausa_curta',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'lenhador_no_cabo_baixo_em_ritmo_lento',
    group: 'Core',
    equipmentCue: 'Cabo',
    equipmentKey: 'low_cable',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_bug_com_carga_leve',
    group: 'Core',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_bug_com_carga_leve_regressivo',
    group: 'Core',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_bug_com_carga_leve_com_pausa_curta',
    group: 'Core',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'dead_bug_com_carga_leve_em_ritmo_lento',
    group: 'Core',
    equipmentCue: 'Halter',
    equipmentKey: 'dumbbells',
  ),
  V099B2StrengthExpectedExercise(
    key: 'hip_thrust_com_barra',
    group: 'Gluteos',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'hip_thrust_com_barra_controlado',
    group: 'Gluteos',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
  V099B2StrengthExpectedExercise(
    key: 'hip_thrust_com_barra_com_pausa',
    group: 'Gluteos',
    equipmentCue: 'Barra',
    equipmentKey: 'barbell',
  ),
];
