import '../models/goal.dart';
import '../services/workout_taxonomy.dart';

class SeedData {
  static final startDate = DateTime(2026, 6, 6);

  static List<String> get workoutTypes => WorkoutTaxonomy.defaultTypeNames;

  static const exercisesByGroup = {
    'Pescoço': [
      'Isometria cervical frontal leve',
      'Isometria cervical lateral leve',
      'Chin tuck',
      'Rotação cervical controlada',
      'Isometria cervical posterior leve',
    ],
    'Trapézio': [
      'Encolhimento de ombros com halteres',
      'Encolhimento de ombros com barra',
      'Encolhimento de ombros na máquina',
      'Remo alto leve',
      'Face pull no cabo',
    ],
    'Ombros': [
      'Press militar com barra em pé',
      'Press militar com halteres',
      'Press militar com barra',
      'Arnold press',
      'Elevação lateral',
      'Elevação frontal',
      'Elevação posterior',
      'Reverse fly',
      'Face pull no cabo',
      'Face pull com elástico',
      'Pull-apart',
      'Mobilidade de ombro com elástico',
      'Wall slides',
      'Rotação externa',
      'Rotação externa com elástico',
      'Rotação interna',
      'Rotação interna com elástico',
      'Y raise',
      'W raise',
      'Scapular push-up',
      'Pike push-up',
      'Elevação no plano da omoplata',
    ],
    'Peito': [
      'Flexão clássica',
      'Flexão com joelhos apoiados',
      'Flexão inclinada',
      'Flexão declinada',
      'Flexão aberta',
      'Flexão arqueiro',
      'Supino com barra',
      'Supino com halteres',
      'Supino inclinado com halteres',
      'Supino inclinado com barra',
      'Supino declinado com halteres',
      'Supino declinado com barra',
      'Supino declinado na máquina',
      'Aberturas com halteres',
      'Aberturas inclinadas com halteres',
      'Aberturas inclinadas no cabo',
      'Aberturas inclinadas com elástico',
      'Squeeze press',
      'Chest press',
      'Dips para peito em paralelas',
      'Dips assistidos para peito na máquina',
      'Crossover no cabo',
      'Pullover com halter',
    ],
    'Costas': [
      'Puxada alta',
      'Puxada alta pega aberta',
      'Puxada alta pega neutra',
      'Puxada alta pega fechada',
      'Remo baixo no cabo',
      'Remo sentado',
      'Remo unilateral com halter',
      'Remo com barra',
      'Remo invertido',
      'Remo invertido em mesa resistente',
      'Pull-up',
      'Scapular pull-up',
      'Dead hang escapular',
      'Face pull no cabo',
      'Pullover no cabo',
      'Pullover com halter',
      'Good morning sem carga',
      'Puxada com braços esticados',
      'Remo com elástico',
    ],
    'Lombar': [
      'Hiperextensão lombar',
      'Hiperextensão no chão',
      'Hiperextensão no banco romano',
      'Superman isométrico',
      'Extensão lombar quadrupede',
      'Good morning com barra',
      'Good morning leve isométrico',
      'Extensão lombar com elástico',
    ],
    'Bíceps': [
      'Curl com barra',
      'Curl com halteres',
      'Curl alternado',
      'Curl martelo',
      'Curl concentrado',
      'Curl inclinado com halteres',
      'Curl inverso',
      'Curl inverso com halteres',
      'Curl Zottman',
      'Curl cruzado no corpo',
      'Curl spider',
      'Curl no cabo',
      'Curl com elástico',
      'Curl 21 com halteres',
      'Curl arrastado com halteres',
      'Curl isométrico',
      'Chin-up',
    ],
    'Tríceps': [
      'Extensão de tríceps no cabo',
      'Extensão acima da cabeça com halter',
      'Tríceps testa com barra EZ',
      'Tríceps testa com halteres',
      'Extensão de tríceps deitado com halteres',
      'Supino fechado',
      'Press fechado com halteres',
      'Tate press',
      'Fundos entre apoios',
      'Flexão fechada',
      'Flexão diamante',
      'Kickback de tríceps',
      'Kickback no cabo',
      'Extensão unilateral de tríceps',
      'Extensão francesa com halter',
      'Extensão francesa com barra EZ',
      'Extensão francesa no cabo',
      'Dips para tríceps',
      'Tríceps no cabo com corda',
      'Tríceps com elástico',
    ],
    'Antebraço/Pega': [
      'Wrist curl',
      'Reverse wrist curl',
      'Farmer walk',
      'Farmer hold',
      'Dead hang',
      'Aperto isométrico',
      'Curl inverso',
      'Pronação com halter',
      'Supinação com halter',
      'Pinch grip',
      'Plate hold',
      'Towel grip hold',
      'Finger curls',
      'Extensão de dedos com elástico',
      'Desvio radial com halter',
      'Desvio ulnar com halter',
      'Suitcase carry',
      'Hold estático com halteres',
      'Rotação controlada com halter leve',
    ],
    'Core': [
      'Prancha',
      'Prancha lateral',
      'Crunch',
      'Reverse crunch',
      'Elevação de pernas',
      'Elevação de joelhos suspenso',
      'Dead bug',
      'Hollow hold',
      'Mountain climbers',
      'Pallof press no cabo',
      'Pallof press com elástico',
      'Russian twist',
      'Bicycle crunch',
      'Bird dog',
      'Side bend',
      'Vacuum abdominal',
      'Flutter kicks',
      'Toe touches',
      'Superman',
      'Lenhador no cabo',
      'Prancha com toque no ombro',
    ],
    'Pernas': [
      'Agachamento com peso corporal',
      'Agachamento para cadeira',
      'Agachamento goblet',
      'Agachamento com halteres ao lado',
      'Agachamento com barra',
      'Agachamento com mochila',
      'Agachamento com garrafão',
      'Agachamento sumo',
      'Agachamento na máquina Smith',
      'Agachamento búlgaro',
      'Agachamento búlgaro com apoio',
      'Extensão de perna',
      'Leg press',
      'Step-up',
      'Wall sit',
      'Lunges',
      'Lunges com halteres',
      'Lunges com mochila',
      'Walking lunges',
      'Peso morto tradicional',
      'Peso morto romeno com halteres',
      'Curl de perna',
      'Good morning leve',
      'Good morning sem carga',
      'Ponte de glúteo',
      'Hip thrust',
      'Hip thrust com apoio',
      'Abdução de anca',
      'Adução de anca',
      'Kickback de glúteo',
      'Gémeos em pé',
      'Gémeos sentado',
      'Elevação de gémeos unilateral',
      'Sóleo sentado',
      'Saltos leves',
      'Elevação tibial',
      'Short foot / doming',
      'Flexão ativa dos dedos do pé',
      'Dorsiflexão do tornozelo com elástico',
      'Inversão do tornozelo com elástico',
      'Eversão do tornozelo com elástico',
      'Flexão da anca em pé com elástico',
      'Copenhagen plank com apoio',
      'Extensão terminal do joelho com elástico',
      'Abdução de anca deitada',
      'Clamshell',
      'Curl nórdico assistido',
      'Peso morto unilateral com halteres',
    ],
    'Cardio': [
      'Marcha no lugar',
      'Jumping jacks',
      'Burpees',
      'Skaters',
      'High knees',
      'Circuito cardio peso corporal',
      'Passadeira caminhada',
      'Passadeira caminhada rápida',
      'Passadeira corrida leve',
      'Passadeira corrida intervalada',
      'Passadeira inclinação',
      'Passadeira inclinação moderada',
      'Passadeira sprints',
      'Passadeira sprints intervalados',
      'Passadeira aquecimento',
      'Passadeira cooldown',
      'Bicicleta ritmo leve',
      'Bicicleta ritmo moderado',
      'Bicicleta intervalos',
      'Bicicleta resistência',
      'Bicicleta aquecimento',
      'Bicicleta cooldown',
      'Elíptica ritmo leve',
      'Elíptica ritmo moderado',
      'Elíptica intervalos',
      'Elíptica resistência',
      'Elíptica aquecimento',
      'Elíptica cooldown',
      'Corda de saltar ritmo leve',
      'Corda de saltar intervalos',
      'Corda de saltar pés alternados',
      'Corda de saltar joelhos altos',
      'Corda de saltar double unders',
      'Caminhada exterior leve',
      'Caminhada exterior moderada',
      'Caminhada exterior rápida',
      'Caminhada exterior em subida',
      'Corrida exterior leve',
      'Corrida exterior moderada',
      'Corrida exterior intervalada',
      'Sprints exterior',
      'Corrida em subida',
      'HIIT peso corporal',
      'HIIT cardio',
      'HIIT passadeira',
      'HIIT bicicleta',
      'HIIT corda',
      'HIIT simples',
      'Circuito cardio leve',
      'Remo ergómetro ritmo contínuo',
      'Remo ergómetro intervalos',
      'Stepper / escadas ritmo contínuo',
      'Stepper / escadas intervalos',
      'Subida de escadas no exterior',
      'Air bike ritmo contínuo',
      'Air bike intervalos',
      'Shadow boxing leve',
      'Shuttle runs / corrida vaivém',
    ],
    'Karate': [
      'Kihon',
      'Kata',
      'Kumite técnico',
      'Sombra de Karate',
      'Drills de deslocamento',
      'Drills de guarda',
      'Pontapés técnicos',
      'Socos técnicos',
      'Mobilidade de anca para Karate',
      'Mobilidade de ombro para Karate',
      'Condicionamento leve para Karate',
      'Treino de bases (dachi)',
      'Bloqueios técnicos (uke)',
      'Esquivas e tai-sabaki',
      'Joelhadas técnicas',
      'Trabalho leve ao saco',
    ],
    'Jiu-Jitsu': [
      'Shrimp / fuga de anca',
      'Ponte de grappling',
      'Technical stand-up',
      'Sprawl',
      'Drills de guarda',
      'Drills de passagem de guarda',
      'Mobilidade de anca para Jiu-Jitsu',
      'Mobilidade de ombro para Jiu-Jitsu',
      'Força de pega para Jiu-Jitsu',
      'Core para Jiu-Jitsu',
      'Condicionamento leve para Jiu-Jitsu',
      'Rolamentos de solo',
      'Breakfalls (ukemi)',
      'Inversão granby com apoio',
    ],
    'Mobilidade': [
      'Mobilidade torácica',
      'Mobilidade de ombro',
      'Mobilidade de anca',
      'Círculos de ombro',
      'Alongamento posterior do ombro',
      'Mobilidade de ombro com toalha',
      'Mobilidade de ombro com cabo de vassoura',
      'Alongamento peitoral',
      'Alongamento peitoral na parede',
      'Alongamento peitoral no canto',
      'Alongamento dorsal',
      'Rotação torácica no chão',
      'Cat-cow',
      'Open book',
      'Alongamento posterior de coxa',
      'Alongamento posterior sentado',
      'Alongamento posterior em pé',
      'Tocar nos pés sentado',
      'Tocar nos pés em pé',
      'Alongamento posterior com perna elevada',
      'Mobilidade dinâmica de posterior',
      'Alongamento glúteos',
      'Alongamento de glúteo sentado',
      'Alongamento figura 4',
      'Pigeon stretch',
      'Alongamento piriforme',
      'Rotação externa da anca no chão',
      'Mobilidade 90/90',
      'Mobilidade dinâmica de anca',
      'Alongamento quadríceps em pé',
      'Alongamento quadríceps de lado',
      'Alongamento gémeos',
      'Alongamento gémeos na parede',
      'Mobilidade de tornozelo na parede',
      'Círculos de tornozelo',
      'Mobilidade de punhos',
      'Extensão de punhos no chão',
      'Flexão de punhos no chão',
      'Alongamento cervical leve',
      'Mobilidade leve de ombros',
      'Mobilidade leve de anca',
      'Respiração diafragmática',
      'Caminhada leve',
      'Relaxamento deitado',
      'Alongamento PNF de isquiotibiais',
      'Alongamento PNF de peitoral na parede',
      'Alongamento de flexores da anca em afundo',
      'Alongamento borboleta de adutores',
      'Alongamento dinâmico global',
      'Alongamento de tríceps atrás da cabeça',
      'Cobra suave no chão',
      'Respiração nasal lenta',
      'Foam roller para pernas',
      'Foam roller para costas',
      'Bola de massagem para pés e glúteos',
      'Arrefecimento pós-treino de força',
      'Arrefecimento pós-artes marciais',
      'Aquecimento dinâmico geral',
    ],
  };

  static final goals = [
    ...[
      'Ganhar massa muscular',
      'Perder gordura',
      'Construir V-shape',
      'Definir abdominal',
      'Ganhar força',
      'Melhorar cardio',
      'Melhorar mobilidade',
      'Melhorar postura',
      'Melhorar performance no Karate',
      'Melhorar performance no Jiu-Jitsu',
      'Recomposição corporal',
      'Manutenção',
    ].map(
      (title) => Goal(
        title: title,
        description: '',
        phase: 'Base',
        category: 'Objetivo inicial',
        metricKey: 'manual',
        isActive: true,
        createdAt: startDate,
      ),
    ),
  ];
}
