import '../models/goal.dart';
import '../services/workout_taxonomy.dart';

class SeedData {
  static final startDate = DateTime(2026, 6, 6);

  static List<String> get workoutTypes => WorkoutTaxonomy.defaultTypeNames;

  static const exercisesByGroup = {
    'Pescoço': [
      'Isometria cervical frontal leve',
      'Isometria cervical lateral leve',
    ],
    'Trapézio': [
      'Encolhimento de ombros com halteres',
      'Face pull',
      'Remo alto leve',
    ],
    'Ombros': [
      'Press militar',
      'Press militar com halteres',
      'Press militar com barra',
      'Arnold press',
      'Elevação lateral',
      'Elevação frontal',
      'Elevação posterior',
      'Reverse fly',
      'Face pull',
      'Rotação externa',
      'Rotação interna',
      'Y raise',
      'W raise',
    ],
    'Peito': [
      'Flexões',
      'Flexões inclinadas',
      'Flexões declinadas',
      'Supino com barra',
      'Supino com halteres',
      'Supino inclinado',
      'Supino declinado',
      'Aberturas com halteres',
      'Aberturas inclinadas',
      'Squeeze press',
      'Chest press',
      'Dips para peito',
      'Crossover no cabo',
      'Pullover com halter',
    ],
    'Costas': [
      'Puxada alta',
      'Puxada alta pega aberta',
      'Puxada alta pega neutra',
      'Puxada alta pega fechada',
      'Remo baixo',
      'Remo sentado',
      'Remo unilateral com halter',
      'Remo com barra',
      'Remo invertido',
      'Pullover no cabo',
      'Pullover com halter',
      'Face pull',
      'Hiperextensão lombar',
      'Peso morto romeno',
    ],
    'Bíceps': [
      'Curl com barra',
      'Curl com halteres',
      'Curl alternado',
      'Curl martelo',
      'Curl concentrado',
      'Curl inclinado',
      'Curl inverso',
      'Curl spider',
      'Curl no cabo',
      'Curl 21',
      'Curl isométrico',
      'Chin-up',
    ],
    'Tríceps': [
      'Extensão de tríceps no cabo',
      'Extensão de tríceps acima da cabeça',
      'Tríceps testa',
      'Supino fechado',
      'Fundos entre apoios',
      'Flexões fechadas',
      'Kickback de tríceps',
      'Extensão unilateral de tríceps',
      'Extensão francesa',
      'Dips para tríceps',
      'Tríceps no cabo com corda',
    ],
    'Antebraço/Pega': [
      'Wrist curl',
      'Reverse wrist curl',
      'Farmer walk',
      'Dead hang',
      'Aperto isométrico',
      'Curl inverso',
      'Pronação com halter',
      'Supinação com halter',
      'Pinch grip',
      'Plate hold',
      'Towel grip hold',
      'Finger curls',
      'Extensão de dedos com elástico',
      'Desvio radial do punho',
      'Desvio ulnar do punho',
    ],
    'Core': [
      'Prancha',
      'Prancha lateral',
      'Crunch',
      'Reverse crunch',
      'Elevação de pernas',
      'Dead bug',
      'Hollow hold',
      'Mountain climbers',
      'Pallof press',
      'Russian twist',
      'Bicycle crunch',
      'Bird dog',
      'Side bend',
      'Vacuum abdominal',
      'Flutter kicks',
      'Toe touches',
    ],
    'Pernas': [
      'Agachamento',
      'Agachamento goblet',
      'Agachamento búlgaro',
      'Extensão de perna',
      'Leg press',
      'Step-up',
      'Wall sit',
      'Lunges',
      'Peso morto tradicional',
      'Curl de perna',
      'Good morning leve',
      'Ponte de glúteo',
      'Hip thrust',
      'Abdução de anca',
      'Adução de anca',
      'Kickback de glúteo',
      'Gémeos em pé',
      'Gémeos sentado',
      'Elevação de gémeos unilateral',
      'Sóleo sentado',
      'Saltos leves',
      'Elevação tibial',
    ],
    'Cardio': [
      'Passadeira caminhada',
      'Passadeira caminhada rápida',
      'Passadeira corrida leve',
      'Passadeira corrida intervalada',
      'Passadeira inclinação',
      'Passadeira sprints intervalados',
      'Passadeira aquecimento',
      'Passadeira cooldown',
      'Bicicleta ritmo leve',
      'Bicicleta ritmo moderado',
      'Bicicleta intervalos',
      'Bicicleta resistência',
      'Bicicleta aquecimento',
      'Bicicleta cooldown',
      'Elíptica ritmo leve',
      'Elíptica ritmo moderado',
      'Elíptica intervalos',
      'Elíptica resistência',
      'Elíptica aquecimento',
      'Elíptica cooldown',
      'Corda de saltar ritmo leve',
      'Corda de saltar intervalos',
      'Corda de saltar pés alternados',
      'Corda de saltar joelhos altos',
      'Corda de saltar double unders',
      'Caminhada exterior leve',
      'Caminhada exterior moderada',
      'Caminhada exterior rápida',
      'Caminhada exterior em subida',
      'Corrida exterior leve',
      'Corrida exterior moderada',
      'Corrida exterior intervalada',
      'Sprints exterior',
      'Corrida em subida',
      'HIIT peso corporal',
      'HIIT cardio',
      'HIIT passadeira',
      'HIIT bicicleta',
      'HIIT corda',
      'HIIT simples',
      'Circuito cardio leve',
    ],
    'Karate': [
      'Kihon',
      'Kata',
      'Kumite técnico',
      'Sombra de Karate',
      'Drills de deslocamento',
      'Drills de guarda',
      'Pontapés técnicos',
      'Socos técnicos',
      'Mobilidade de anca para Karate',
      'Mobilidade de ombro para Karate',
      'Condicionamento leve para Karate',
    ],
    'Jiu-Jitsu': [
      'Shrimp / fuga de anca',
      'Ponte de grappling',
      'Technical stand-up',
      'Drills de guarda',
      'Drills de passagem de guarda',
      'Mobilidade de anca para Jiu-Jitsu',
      'Mobilidade de ombro para Jiu-Jitsu',
      'Força de pega para Jiu-Jitsu',
      'Core para Jiu-Jitsu',
      'Condicionamento leve para Jiu-Jitsu',
    ],
    'Mobilidade': [
      'Mobilidade torácica',
      'Mobilidade de ombro',
      'Mobilidade de anca',
      'Alongamento posterior de coxa',
      'Respiração diafragmática',
    ],
  };

  static final goals = [
    ...[
      'Ganhar massa muscular',
      'Perder gordura',
      'Construir V-shape',
      'Definir abdominal',
      'Ganhar força',
      'Melhorar cardio',
      'Melhorar mobilidade',
      'Melhorar postura',
      'Melhorar performance no Karate',
      'Melhorar performance no Jiu-Jitsu',
      'Recomposição corporal',
      'Manutenção',
    ].map(
      (title) => Goal(
        title: title,
        description: '',
        phase: 'Base',
        category: 'Objetivo inicial',
        metricKey: 'manual',
        isActive: true,
        createdAt: startDate,
      ),
    ),
  ];
}
