import 'v100_catalog_domain_data.dart';

const v099b1StrengthDomainEntries = <V100CatalogDomainEntryData>[
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_reto_com_barra',
    name: 'Supino reto com barra',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'desenvolver forca no empurrar horizontal com barra',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_reto_com_barra_controlado',
    name: 'Supino reto com barra controlado',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar a tecnica do supino reto com barra',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_reto_com_barra_com_pausa',
    name: 'Supino reto com barra com pausa',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'reforcar controlo no fundo do supino reto',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_reto_com_barra_em_tempo_lento',
    name: 'Supino reto com barra em tempo lento',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar tempo sob tensao no supino reto',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_declinado_com_barra_controlado',
    name: 'Supino declinado com barra controlado',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco declinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar o supino declinado com barra sem perder escapulas',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_inclinado_com_barra_controlado',
    name: 'Supino inclinado com barra controlado',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar o supino inclinado sem perder escapulas',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_inclinado_com_barra_com_pausa',
    name: 'Supino inclinado com barra com pausa',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'reforcar estabilidade no fundo do supino inclinado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'peito',
    conceptId: 'supino_inclinado_com_barra_em_tempo_lento',
    name: 'Supino inclinado com barra em tempo lento',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo e tempo sob tensao no supino inclinado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_a_frente',
    name: 'Puxada alta a frente',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar puxada vertical para dorsais',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_a_frente_controlado',
    name: 'Puxada alta a frente controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar a puxada vertical sem embalar',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_a_frente_com_pausa',
    name: 'Puxada alta a frente com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'melhorar controlo escapular na puxada alta',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_a_frente_em_tempo_lento',
    name: 'Puxada alta a frente em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar tempo sob tensao na puxada alta',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_com_pegada_neutra',
    name: 'Puxada alta com pegada neutra',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown com pega neutra',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar dorsais com pega neutra',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_com_pegada_neutra_controlado',
    name: 'Puxada alta com pegada neutra controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown com pega neutra',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar a puxada neutra sem compensar tronco',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_com_pegada_neutra_com_pausa',
    name: 'Puxada alta com pegada neutra com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown com pega neutra',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar a puxada neutra com escapulas controladas',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'puxada_alta_com_pegada_neutra_em_tempo_lento',
    name: 'Puxada alta com pegada neutra em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Lat pulldown com pega neutra',
    primaryMuscle: 'grande dorsal',
    secondaryMuscles: 'biceps; redondo maior; trapezio medio e inferior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo na puxada neutra',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_sentada_no_cabo',
    name: 'Remada sentada no cabo',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; trapezio medio',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar remada horizontal no cabo',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_sentada_no_cabo_controlado',
    name: 'Remada sentada no cabo controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; trapezio medio',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar a remada sentada sem balanco',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_sentada_no_cabo_com_pausa',
    name: 'Remada sentada no cabo com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; trapezio medio',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar a remada com escapulas aproximadas',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_sentada_no_cabo_em_tempo_lento',
    name: 'Remada sentada no cabo em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; trapezio medio',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar tempo sob tensao na remada sentada',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_baixa_unilateral',
    name: 'Remada baixa unilateral',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar remada unilateral com cabo',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_baixa_unilateral_controlado',
    name: 'Remada baixa unilateral controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar remada unilateral sem rodar tronco',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_baixa_unilateral_com_pausa',
    name: 'Remada baixa unilateral com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar a remada unilateral com tronco estavel',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'costas',
    conceptId: 'remada_baixa_unilateral_em_tempo_lento',
    name: 'Remada baixa unilateral em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Cabo / polia baixa',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'biceps; romboides; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo na remada unilateral',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_de_ombro_com_halteres',
    name: 'Press de ombro com halteres',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'desenvolver press vertical com halteres',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_de_ombro_com_halteres_controlado',
    name: 'Press de ombro com halteres controlado',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar press vertical sem arquear lombar',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_de_ombro_com_halteres_com_pausa',
    name: 'Press de ombro com halteres com pausa',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar o press de ombro com halteres',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_de_ombro_com_halteres_em_tempo_lento',
    name: 'Press de ombro com halteres em tempo lento',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo no press de ombro',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_na_smith_machine',
    name: 'Press na Smith machine',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Smith machine',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar press vertical guiado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_na_smith_machine_controlado',
    name: 'Press na Smith machine controlado',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Smith machine',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar press guiado na Smith machine',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_na_smith_machine_com_pausa',
    name: 'Press na Smith machine com pausa',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Smith machine',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar press guiado com ombros organizados',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'ombros',
    conceptId: 'press_na_smith_machine_em_tempo_lento',
    name: 'Press na Smith machine em tempo lento',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Smith machine',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core estabilizador',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo no press guiado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_45_graus',
    name: 'Leg press 45 graus',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press 45 graus',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'treinar empurrar de pernas no leg press 45 graus',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_45_graus_controlado',
    name: 'Leg press 45 graus controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press 45 graus',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'controlar amplitude no leg press 45 graus',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_45_graus_com_pausa',
    name: 'Leg press 45 graus com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press 45 graus',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'pausar leg press sem perder joelhos alinhados',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_45_graus_em_tempo_lento',
    name: 'Leg press 45 graus em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press 45 graus',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'aumentar controlo no leg press 45 graus',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_horizontal',
    name: 'Leg press horizontal',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press horizontal',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'treinar empurrar de pernas no leg press horizontal',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_horizontal_controlado',
    name: 'Leg press horizontal controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press horizontal',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'controlar amplitude no leg press horizontal',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_horizontal_com_pausa',
    name: 'Leg press horizontal com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press horizontal',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'pausar leg press horizontal sem perder postura',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'leg_press_horizontal_em_tempo_lento',
    name: 'Leg press horizontal em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg press horizontal',
    primaryMuscle: 'quadriceps e gluteos',
    secondaryMuscles: 'isquiotibiais; adutores; gemeos',
    joint: 'joelho; anca',
    goal: 'aumentar controlo no leg press horizontal',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_na_maquina',
    name: 'Extensao de pernas na maquina',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'isolar quadriceps na maquina de extensao',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_na_maquina_controlado',
    name: 'Extensao de pernas na maquina controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'controlar extensao de joelho na maquina',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_na_maquina_com_pausa',
    name: 'Extensao de pernas na maquina com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'pausar extensao de pernas no topo com controlo',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_na_maquina_em_tempo_lento',
    name: 'Extensao de pernas na maquina em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'aumentar tempo sob tensao na extensao de pernas',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_unilateral',
    name: 'Extensao de pernas unilateral',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'treinar quadriceps de forma unilateral',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_unilateral_controlado',
    name: 'Extensao de pernas unilateral controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'controlar extensao unilateral de joelho',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_unilateral_com_pausa',
    name: 'Extensao de pernas unilateral com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'pausar extensao unilateral com controlo',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'quadriceps',
    conceptId: 'extensao_de_pernas_unilateral_em_tempo_lento',
    name: 'Extensao de pernas unilateral em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Extensao de pernas na maquina',
    primaryMuscle: 'quadriceps',
    secondaryMuscles: 'core leve',
    joint: 'joelho',
    goal: 'aumentar controlo na extensao unilateral',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_sentado',
    name: 'Leg curl sentado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl sentado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'treinar flexao do joelho sentado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_sentado_controlado',
    name: 'Leg curl sentado controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl sentado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'controlar leg curl sentado sem embalar',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_sentado_com_pausa',
    name: 'Leg curl sentado com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl sentado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'pausar flexao do joelho no leg curl sentado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_sentado_em_tempo_lento',
    name: 'Leg curl sentado em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl sentado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'aumentar controlo no leg curl sentado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_deitado',
    name: 'Leg curl deitado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl deitado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'treinar flexao do joelho deitado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_deitado_controlado',
    name: 'Leg curl deitado controlado',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl deitado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'controlar leg curl deitado sem levantar anca',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_deitado_com_pausa',
    name: 'Leg curl deitado com pausa',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl deitado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'pausar flexao do joelho no leg curl deitado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'posterior da coxa e gemeos',
    conceptId: 'leg_curl_deitado_em_tempo_lento',
    name: 'Leg curl deitado em tempo lento',
    contextKey: 'pernas',
    primaryType: 'musculacao',
    equipment: 'Leg curl deitado',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos estabilizadores',
    joint: 'joelho',
    goal: 'aumentar controlo no leg curl deitado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'core e lombar',
    conceptId: 'ab_wheel_a_partir_dos_joelhos',
    name: 'Ab wheel a partir dos joelhos',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Ab wheel e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'serratil; ombros; grande dorsal estabilizador',
    joint: 'coluna; ombro',
    goal: 'treinar anti-extensao do core com roda abdominal',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'core e lombar',
    conceptId: 'ab_wheel_a_partir_dos_joelhos_regressivo',
    name: 'Ab wheel a partir dos joelhos regressivo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Ab wheel e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'serratil; ombros; grande dorsal estabilizador',
    joint: 'coluna; ombro',
    goal: 'usar uma versao mais curta do ab wheel',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'core e lombar',
    conceptId: 'ab_wheel_a_partir_dos_joelhos_com_pausa_curta',
    name: 'Ab wheel a partir dos joelhos com pausa curta',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Ab wheel e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'serratil; ombros; grande dorsal estabilizador',
    joint: 'coluna; ombro',
    goal: 'pausar ab wheel mantendo lombar neutra',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'core e lombar',
    conceptId: 'ab_wheel_a_partir_dos_joelhos_em_ritmo_lento',
    name: 'Ab wheel a partir dos joelhos em ritmo lento',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Ab wheel e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'serratil; ombros; grande dorsal estabilizador',
    joint: 'coluna; ombro',
    goal: 'aumentar controlo no ab wheel',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'antebraco e pegada',
    conceptId: 'farmer_walk_com_halteres',
    name: 'Farmer walk com halteres',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'treinar pega e transporte carregado',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'antebraco e pegada',
    conceptId: 'farmer_walk_com_halteres_regressivo',
    name: 'Farmer walk com halteres regressivo',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'usar carga e distancia reduzidas no farmer walk',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'antebraco e pegada',
    conceptId: 'farmer_walk_com_halteres_com_pausa_curta',
    name: 'Farmer walk com halteres com pausa curta',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'pausar farmer walk sem perder postura',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B1',
    section: 'antebraco e pegada',
    conceptId: 'farmer_walk_com_halteres_em_ritmo_lento',
    name: 'Farmer walk com halteres em ritmo lento',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'controlar passos e pega no farmer walk',
    priority: 'B1',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
];
