import 'v100_catalog_domain_data.dart';

const v099b2StrengthDomainEntries = <V100CatalogDomainEntryData>[
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_declinado_com_barra_com_pausa',
    name: 'Supino declinado com barra com pausa',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco declinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'reforcar controlo no fundo do supino declinado',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_declinado_com_barra_em_tempo_lento',
    name: 'Supino declinado com barra em tempo lento',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Barra e banco declinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar tempo sob tensao no supino declinado',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_reto_com_halteres',
    name: 'Supino reto com halteres',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco plano',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar empurrar horizontal com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_reto_com_halteres_controlado',
    name: 'Supino reto com halteres controlado',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco plano',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar supino reto com halteres sem perder escapulas',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_reto_com_halteres_com_pausa',
    name: 'Supino reto com halteres com pausa',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco plano',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar o supino reto com halteres no fundo seguro',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_reto_com_halteres_em_tempo_lento',
    name: 'Supino reto com halteres em tempo lento',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco plano',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo no supino reto com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_inclinado_com_halteres_controlado',
    name: 'Supino inclinado com halteres controlado',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar o supino inclinado com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_inclinado_com_halteres_com_pausa',
    name: 'Supino inclinado com halteres com pausa',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar o supino inclinado com halteres sem compensar',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'peito',
    conceptId: 'supino_inclinado_com_halteres_em_tempo_lento',
    name: 'Supino inclinado com halteres em tempo lento',
    contextKey: 'peito',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'triceps; deltoide anterior; serratil anterior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar tempo sob tensao no supino inclinado com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_curvada_com_barra',
    name: 'Remada curvada com barra',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; trapezio medio; biceps; lombar',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'treinar remada horizontal com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_curvada_com_barra_controlado',
    name: 'Remada curvada com barra controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; trapezio medio; biceps; lombar',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'controlar remada curvada sem perder lombar neutra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_curvada_com_barra_com_pausa',
    name: 'Remada curvada com barra com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; trapezio medio; biceps; lombar',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'pausar a remada curvada com escapulas ativas',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_curvada_com_barra_em_tempo_lento',
    name: 'Remada curvada com barra em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; trapezio medio; biceps; lombar',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'aumentar controlo na remada curvada com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_unilateral_com_halter',
    name: 'Remada unilateral com halter',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Halter e banco',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; biceps; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'treinar remada unilateral com apoio',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_unilateral_com_halter_controlado',
    name: 'Remada unilateral com halter controlado',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Halter e banco',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; biceps; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'controlar remada unilateral sem rodar tronco',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_unilateral_com_halter_com_pausa',
    name: 'Remada unilateral com halter com pausa',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Halter e banco',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; biceps; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'pausar remada unilateral com escapula controlada',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'costas',
    conceptId: 'remada_unilateral_com_halter_em_tempo_lento',
    name: 'Remada unilateral com halter em tempo lento',
    contextKey: 'costas',
    primaryType: 'musculacao',
    equipment: 'Halter e banco',
    primaryMuscle: 'costas medias e dorsais',
    secondaryMuscles: 'romboides; biceps; core anti-rotacao',
    joint: 'ombro; cotovelo; escapula; coluna',
    goal: 'aumentar controlo na remada unilateral',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_militar_com_barra_controlado',
    name: 'Press militar com barra controlado',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar press vertical com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_militar_com_barra_com_pausa',
    name: 'Press militar com barra com pausa',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar press militar com tronco estavel',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_militar_com_barra_em_tempo_lento',
    name: 'Press militar com barra em tempo lento',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; trapezio superior; core',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo no press militar com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_arnold',
    name: 'Press Arnold',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; rotadores externos; trapezio superior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'treinar press de ombro com rotacao controlada',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_arnold_controlado',
    name: 'Press Arnold controlado',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; rotadores externos; trapezio superior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'controlar a transicao do press Arnold',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_arnold_com_pausa',
    name: 'Press Arnold com pausa',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; rotadores externos; trapezio superior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'pausar press Arnold sem encolher ombros',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'ombros',
    conceptId: 'press_arnold_em_tempo_lento',
    name: 'Press Arnold em tempo lento',
    contextKey: 'ombros',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'deltoides',
    secondaryMuscles: 'triceps; rotadores externos; trapezio superior',
    joint: 'ombro; cotovelo; escapula',
    goal: 'aumentar controlo no press Arnold',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_biceps_com_barra',
    name: 'Curl biceps com barra',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'treinar flexao do cotovelo com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_biceps_com_barra_controlado',
    name: 'Curl biceps com barra controlado',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'controlar curl com barra sem balanco',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_biceps_com_barra_com_pausa',
    name: 'Curl biceps com barra com pausa',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'pausar curl com barra mantendo cotovelos estaveis',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_biceps_com_barra_em_tempo_lento',
    name: 'Curl biceps com barra em tempo lento',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Barra',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'aumentar controlo no curl com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_alternado_com_halteres',
    name: 'Curl alternado com halteres',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'treinar flexao alternada com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_alternado_com_halteres_controlado',
    name: 'Curl alternado com halteres controlado',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'controlar curl alternado sem rodar tronco',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_alternado_com_halteres_com_pausa',
    name: 'Curl alternado com halteres com pausa',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'pausar curl alternado com halteres',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_alternado_com_halteres_em_tempo_lento',
    name: 'Curl alternado com halteres em tempo lento',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'aumentar controlo no curl alternado',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_martelo_controlado',
    name: 'Curl martelo controlado',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'controlar curl martelo com pega neutra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_martelo_com_pausa',
    name: 'Curl martelo com pausa',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'pausar curl martelo sem perder punho neutro',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_martelo_em_tempo_lento',
    name: 'Curl martelo em tempo lento',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho',
    goal: 'aumentar controlo no curl martelo',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_inclinado_no_banco',
    name: 'Curl inclinado no banco',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho; ombro',
    goal: 'treinar biceps com ombro em extensao controlada',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_inclinado_no_banco_controlado',
    name: 'Curl inclinado no banco controlado',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho; ombro',
    goal: 'controlar curl inclinado sem balancar ombros',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_inclinado_no_banco_com_pausa',
    name: 'Curl inclinado no banco com pausa',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho; ombro',
    goal: 'pausar curl inclinado com cotovelos estaveis',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'biceps',
    conceptId: 'curl_inclinado_no_banco_em_tempo_lento',
    name: 'Curl inclinado no banco em tempo lento',
    contextKey: 'biceps',
    primaryType: 'musculacao',
    equipment: 'Halteres e banco inclinado',
    primaryMuscle: 'biceps braquial',
    secondaryMuscles: 'braquial; braquiorradial; antebraco',
    joint: 'cotovelo; punho; ombro',
    goal: 'aumentar controlo no curl inclinado',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'suitcase_carry_unilateral',
    name: 'Suitcase carry unilateral',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'treinar pega unilateral e anti-inclinacao',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'suitcase_carry_unilateral_regressivo',
    name: 'Suitcase carry unilateral regressivo',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'reduzir distancia e carga no suitcase carry',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'suitcase_carry_unilateral_com_pausa_curta',
    name: 'Suitcase carry unilateral com pausa curta',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'pausar suitcase carry sem inclinar tronco',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'suitcase_carry_unilateral_em_ritmo_lento',
    name: 'Suitcase carry unilateral em ritmo lento',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Halteres e espaco livre',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'trapezio; core lateral; gluteos estabilizadores',
    joint: 'punho; ombro; coluna',
    goal: 'controlar passos e pega no suitcase carry',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'dead_hang_na_barra',
    name: 'Dead hang na barra',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Barra fixa',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'escapulas; grande dorsal; core',
    joint: 'punho; ombro; escapula',
    goal: 'treinar suspensao e pega na barra fixa',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'dead_hang_na_barra_regressivo',
    name: 'Dead hang na barra regressivo',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Barra fixa',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'escapulas; grande dorsal; core',
    joint: 'punho; ombro; escapula',
    goal: 'reduzir duracao da suspensao na barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'dead_hang_na_barra_com_pausa_curta',
    name: 'Dead hang na barra com pausa curta',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Barra fixa',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'escapulas; grande dorsal; core',
    joint: 'punho; ombro; escapula',
    goal: 'segurar suspensao curta com escapulas controladas',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'antebraco_pegada',
    conceptId: 'dead_hang_na_barra_em_ritmo_lento',
    name: 'Dead hang na barra em ritmo lento',
    contextKey: 'antebraco_pega',
    primaryType: 'musculacao',
    equipment: 'Barra fixa',
    primaryMuscle: 'flexores do antebraco',
    secondaryMuscles: 'escapulas; grande dorsal; core',
    joint: 'punho; ombro; escapula',
    goal: 'entrar e sair da suspensao com controlo',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'pallof_press_no_cabo_regressivo',
    name: 'Pallof press no cabo regressivo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; transverso abdominal; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'treinar anti-rotacao com menor alavanca',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'pallof_press_no_cabo_com_pausa_curta',
    name: 'Pallof press no cabo com pausa curta',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; transverso abdominal; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'pausar Pallof press mantendo tronco estavel',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'pallof_press_no_cabo_em_ritmo_lento',
    name: 'Pallof press no cabo em ritmo lento',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; transverso abdominal; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'controlar anti-rotacao no Pallof press',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_alto',
    name: 'Lenhador no cabo alto',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo alto',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'treinar rotacao controlada do tronco no cabo alto',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_alto_regressivo',
    name: 'Lenhador no cabo alto regressivo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo alto',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'reduzir amplitude no lenhador alto',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_alto_com_pausa_curta',
    name: 'Lenhador no cabo alto com pausa curta',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo alto',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'pausar lenhador alto com bacia estavel',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_alto_em_ritmo_lento',
    name: 'Lenhador no cabo alto em ritmo lento',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo alto',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'controlar rotacao no lenhador alto',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_baixo',
    name: 'Lenhador no cabo baixo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'treinar rotacao controlada do tronco no cabo baixo',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_baixo_regressivo',
    name: 'Lenhador no cabo baixo regressivo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'reduzir amplitude no lenhador baixo',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_baixo_com_pausa_curta',
    name: 'Lenhador no cabo baixo com pausa curta',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'pausar lenhador baixo com bacia estavel',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'lenhador_no_cabo_baixo_em_ritmo_lento',
    name: 'Lenhador no cabo baixo em ritmo lento',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Cabo baixo',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'obliquos; dorsais; gluteos',
    joint: 'coluna; anca; ombro',
    goal: 'controlar rotacao no lenhador baixo',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'dead_bug_com_carga_leve',
    name: 'Dead bug com carga leve',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Halter leve e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'transverso abdominal; flexores da anca; ombros',
    joint: 'coluna; anca; ombro',
    goal: 'treinar anti-extensao com carga leve',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'dead_bug_com_carga_leve_regressivo',
    name: 'Dead bug com carga leve regressivo',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Halter leve e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'transverso abdominal; flexores da anca; ombros',
    joint: 'coluna; anca; ombro',
    goal: 'reduzir alavanca no dead bug com carga leve',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'dead_bug_com_carga_leve_com_pausa_curta',
    name: 'Dead bug com carga leve com pausa curta',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Halter leve e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'transverso abdominal; flexores da anca; ombros',
    joint: 'coluna; anca; ombro',
    goal: 'pausar dead bug mantendo lombar controlada',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'core',
    conceptId: 'dead_bug_com_carga_leve_em_ritmo_lento',
    name: 'Dead bug com carga leve em ritmo lento',
    contextKey: 'core',
    primaryType: 'musculacao',
    equipment: 'Halter leve e tapete',
    primaryMuscle: 'core anterior',
    secondaryMuscles: 'transverso abdominal; flexores da anca; ombros',
    joint: 'coluna; anca; ombro',
    goal: 'controlar dead bug com carga leve',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'gluteos',
    conceptId: 'hip_thrust_com_barra',
    name: 'Hip thrust com barra',
    contextKey: 'gluteos',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'gluteo maximo',
    secondaryMuscles: 'gluteo medio; isquiotibiais; core; quadriceps',
    joint: 'anca; joelho; coluna',
    goal: 'treinar extensao da anca com barra',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'gluteos',
    conceptId: 'hip_thrust_com_barra_controlado',
    name: 'Hip thrust com barra controlado',
    contextKey: 'gluteos',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'gluteo maximo',
    secondaryMuscles: 'gluteo medio; isquiotibiais; core; quadriceps',
    joint: 'anca; joelho; coluna',
    goal: 'controlar hip thrust com barra sem arquear lombar',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B2',
    section: 'gluteos',
    conceptId: 'hip_thrust_com_barra_com_pausa',
    name: 'Hip thrust com barra com pausa',
    contextKey: 'gluteos',
    primaryType: 'musculacao',
    equipment: 'Barra e banco',
    primaryMuscle: 'gluteo maximo',
    secondaryMuscles: 'gluteo medio; isquiotibiais; core; quadriceps',
    joint: 'anca; joelho; coluna',
    goal: 'pausar hip thrust no topo com gluteos ativos',
    priority: 'B2',
    safety:
        'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.',
  ),
];
