import 'v100_catalog_domain_data.dart';

class _B4AActivationSeed {
  const _B4AActivationSeed(
    this.name,
    this.section,
    this.equipment,
    this.primaryMuscle,
    this.secondaryMuscles,
    this.joint,
    this.goal,
  );

  final String name;
  final String section;
  final String equipment;
  final String primaryMuscle;
  final String secondaryMuscles;
  final String joint;
  final String goal;
}

const _safety =
    'Baixa fadiga, respiracao continua e paragem imediata se houver dor aguda, formigueiro ou perda de controlo.';

const _gluteEquipment = 'Mini band, peso corporal e tapete opcional';
const _coreEquipment = 'Peso corporal, tapete e elastico opcional';
const _ankleEquipment = 'Peso corporal, parede, toalha e elastico opcional';

const _b4aActivationSeeds = <_B4AActivationSeed>[
  _B4AActivationSeed(
    'Clamshell com mini band',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; rotadores externos da anca; core leve',
    'anca',
    'acordar abdutores e rotadores externos da anca antes do treino',
  ),
  _B4AActivationSeed(
    'Clamshell com mini band regressivo',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; rotadores externos da anca; core leve',
    'anca',
    'reduzir amplitude no clamshell mantendo controlo da bacia',
  ),
  _B4AActivationSeed(
    'Clamshell com mini band com pausa curta',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; rotadores externos da anca; core leve',
    'anca',
    'pausar o clamshell sem rodar a lombar',
  ),
  _B4AActivationSeed(
    'Clamshell com mini band em ritmo lento',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; rotadores externos da anca; core leve',
    'anca',
    'controlar subida e descida do clamshell com baixa fadiga',
  ),
  _B4AActivationSeed(
    'Abducao lateral de anca deitado',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; tensor da fascia lata; core leve',
    'anca',
    'ativar abdutores da anca com perna estendida e pelvis estavel',
  ),
  _B4AActivationSeed(
    'Abducao lateral de anca deitado regressivo',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; tensor da fascia lata; core leve',
    'anca',
    'usar amplitude pequena na abducao lateral de anca',
  ),
  _B4AActivationSeed(
    'Abducao lateral de anca deitado com pausa curta',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; tensor da fascia lata; core leve',
    'anca',
    'pausar a abducao lateral sem inclinar o tronco',
  ),
  _B4AActivationSeed(
    'Abducao lateral de anca deitado em ritmo lento',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; tensor da fascia lata; core leve',
    'anca',
    'aumentar controlo dos abdutores da anca em ritmo lento',
  ),
  _B4AActivationSeed(
    'Ponte de gluteos com mini band',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core leve',
    'anca; joelho; coluna',
    'ativar gluteos mantendo joelhos alinhados contra a mini band',
  ),
  _B4AActivationSeed(
    'Ponte de gluteos com mini band regressivo',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core leve',
    'anca; joelho; coluna',
    'reduzir amplitude na ponte sem arquear a lombar',
  ),
  _B4AActivationSeed(
    'Ponte de gluteos com mini band com pausa curta',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core leve',
    'anca; joelho; coluna',
    'pausar no topo da ponte com costelas controladas',
  ),
  _B4AActivationSeed(
    'Ponte de gluteos com mini band em ritmo lento',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core leve',
    'anca; joelho; coluna',
    'subir e descer a ponte lentamente sem perder alinhamento',
  ),
  _B4AActivationSeed(
    'Ponte unilateral regressiva',
    'gluteos e anca',
    'Peso corporal, tapete e apoio opcional',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core anti-rotacao',
    'anca; joelho; coluna',
    'preparar ponte unilateral com pouca amplitude e bacia nivelada',
  ),
  _B4AActivationSeed(
    'Ponte unilateral regressiva regressivo',
    'gluteos e anca',
    'Peso corporal, tapete e apoio opcional',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core anti-rotacao',
    'anca; joelho; coluna',
    'simplificar a ponte unilateral usando apoio parcial do outro pe',
  ),
  _B4AActivationSeed(
    'Ponte unilateral regressiva com pausa curta',
    'gluteos e anca',
    'Peso corporal, tapete e apoio opcional',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core anti-rotacao',
    'anca; joelho; coluna',
    'pausar a ponte unilateral regressiva sem rodar a bacia',
  ),
  _B4AActivationSeed(
    'Ponte unilateral regressiva em ritmo lento',
    'gluteos e anca',
    'Peso corporal, tapete e apoio opcional',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core anti-rotacao',
    'anca; joelho; coluna',
    'controlar ponte unilateral regressiva em cadencia lenta',
  ),
  _B4AActivationSeed(
    'Monster walk curto',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo maximo; abdutores da anca; core leve',
    'anca; joelho; tornozelo',
    'ativar gluteos com passos curtos e joelhos alinhados',
  ),
  _B4AActivationSeed(
    'Monster walk curto regressivo',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo maximo; abdutores da anca; core leve',
    'anca; joelho; tornozelo',
    'reduzir distancia dos passos no monster walk',
  ),
  _B4AActivationSeed(
    'Monster walk curto com pausa curta',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo maximo; abdutores da anca; core leve',
    'anca; joelho; tornozelo',
    'pausar cada passo do monster walk sem colapsar joelhos',
  ),
  _B4AActivationSeed(
    'Monster walk curto em ritmo lento',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo maximo; abdutores da anca; core leve',
    'anca; joelho; tornozelo',
    'controlar o monster walk com passos lentos e curtos',
  ),
  _B4AActivationSeed(
    'Lateral band walk controlado',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; gluteo maximo; core leve',
    'anca; joelho; tornozelo',
    'ativar abdutores da anca com passos laterais controlados',
  ),
  _B4AActivationSeed(
    'Lateral band walk regressivo',
    'gluteos e anca',
    _gluteEquipment,
    'gluteo medio',
    'gluteo minimo; gluteo maximo; core leve',
    'anca; joelho; tornozelo',
    'reduzir tensao e amplitude no lateral band walk',
  ),
  _B4AActivationSeed(
    'Dead bug com expiracao guiada',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal',
    'reto abdominal; obliquos; flexores da anca',
    'coluna; anca; ombro',
    'ativar core anterior coordenando movimento lento, controlo lombar e expiracao guiada',
  ),
  _B4AActivationSeed(
    'Dead bug com expiracao regressivo',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal',
    'reto abdominal; obliquos; flexores da anca',
    'coluna; anca; ombro',
    'reduzir alavanca no dead bug mantendo lombar neutra',
  ),
  _B4AActivationSeed(
    'Dead bug com expiracao com pausa curta',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal',
    'reto abdominal; obliquos; flexores da anca',
    'coluna; anca; ombro',
    'pausar o dead bug no ponto controlado com expiracao',
  ),
  _B4AActivationSeed(
    'Dead bug com expiracao em ritmo lento',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal',
    'reto abdominal; obliquos; flexores da anca',
    'coluna; anca; ombro',
    'controlar o dead bug em cadencia lenta sem arquear a lombar',
  ),
  _B4AActivationSeed(
    'Bird dog com pausa',
    'core, ombros e escapulas',
    _coreEquipment,
    'multifidos e transverso abdominal',
    'gluteos; deltoide posterior; estabilizadores escapulares',
    'coluna; anca; ombro',
    'ativar estabilidade cruzada entre tronco, anca e ombro',
  ),
  _B4AActivationSeed(
    'Bird dog com pausa regressivo',
    'core, ombros e escapulas',
    _coreEquipment,
    'multifidos e transverso abdominal',
    'gluteos; deltoide posterior; estabilizadores escapulares',
    'coluna; anca; ombro',
    'reduzir alcance no bird dog mantendo quadris nivelados',
  ),
  _B4AActivationSeed(
    'Bird dog com pausa com pausa curta',
    'core, ombros e escapulas',
    _coreEquipment,
    'multifidos e transverso abdominal',
    'gluteos; deltoide posterior; estabilizadores escapulares',
    'coluna; anca; ombro',
    'pausar bird dog com tronco estavel e pescoco neutro',
  ),
  _B4AActivationSeed(
    'Bird dog com pausa em ritmo lento',
    'core, ombros e escapulas',
    _coreEquipment,
    'multifidos e transverso abdominal',
    'gluteos; deltoide posterior; estabilizadores escapulares',
    'coluna; anca; ombro',
    'fazer bird dog lento sem rodar a bacia',
  ),
  _B4AActivationSeed(
    'Pallof press leve com elastico',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal e obliquos',
    'gluteos; serratil anterior; deltoides',
    'coluna; anca; ombro',
    'ativar anti-rotacao com elastico leve',
  ),
  _B4AActivationSeed(
    'Pallof press leve com elastico regressivo',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal e obliquos',
    'gluteos; serratil anterior; deltoides',
    'coluna; anca; ombro',
    'reduzir tensao ou aproximar os pes no pallof press leve',
  ),
  _B4AActivationSeed(
    'Pallof press leve com elastico com pausa curta',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal e obliquos',
    'gluteos; serratil anterior; deltoides',
    'coluna; anca; ombro',
    'pausar a extensao do pallof press sem rodar o tronco',
  ),
  _B4AActivationSeed(
    'Pallof press leve com elastico em ritmo lento',
    'core, ombros e escapulas',
    _coreEquipment,
    'transverso abdominal e obliquos',
    'gluteos; serratil anterior; deltoides',
    'coluna; anca; ombro',
    'controlar ida e volta do pallof press com elastico leve',
  ),
  _B4AActivationSeed(
    'Prancha curta com joelhos',
    'core, ombros e escapulas',
    _coreEquipment,
    'core anterior',
    'serratil anterior; gluteos; deltoides',
    'coluna; ombro; anca',
    'ativar bracing com prancha curta e apoio dos joelhos',
  ),
  _B4AActivationSeed(
    'Prancha curta com joelhos regressivo',
    'core, ombros e escapulas',
    _coreEquipment,
    'core anterior',
    'serratil anterior; gluteos; deltoides',
    'coluna; ombro; anca',
    'reduzir duracao da prancha curta com joelhos',
  ),
  _B4AActivationSeed(
    'Prancha curta com joelhos com pausa curta',
    'core, ombros e escapulas',
    _coreEquipment,
    'core anterior',
    'serratil anterior; gluteos; deltoides',
    'coluna; ombro; anca',
    'pausar a prancha curta mantendo costelas baixas',
  ),
  _B4AActivationSeed(
    'Prancha curta com joelhos em ritmo lento',
    'core, ombros e escapulas',
    _coreEquipment,
    'core anterior',
    'serratil anterior; gluteos; deltoides',
    'coluna; ombro; anca',
    'entrar e sair da prancha curta com controlo',
  ),
  _B4AActivationSeed(
    'Scapular push-up regressivo',
    'core, ombros e escapulas',
    _coreEquipment,
    'serratil anterior',
    'trapezio medio; trapezio inferior; peitoral menor; core leve',
    'escapula; ombro; cotovelo',
    'ativar protracao e retracao escapular com pouca carga',
  ),
  _B4AActivationSeed(
    'Scapular push-up regressivo nivel inicial',
    'core, ombros e escapulas',
    _coreEquipment,
    'serratil anterior',
    'trapezio medio; trapezio inferior; peitoral menor; core leve',
    'escapula; ombro; cotovelo',
    'simplificar o scapular push-up com apoio alto ou joelhos',
  ),
  _B4AActivationSeed(
    'Scapular push-up regressivo com pausa curta',
    'core, ombros e escapulas',
    _coreEquipment,
    'serratil anterior',
    'trapezio medio; trapezio inferior; peitoral menor; core leve',
    'escapula; ombro; cotovelo',
    'pausar a protracao escapular sem dobrar cotovelos',
  ),
  _B4AActivationSeed(
    'Scapular push-up regressivo em ritmo lento',
    'core, ombros e escapulas',
    _coreEquipment,
    'serratil anterior',
    'trapezio medio; trapezio inferior; peitoral menor; core leve',
    'escapula; ombro; cotovelo',
    'controlar o deslizamento das escapulas em ritmo lento',
  ),
  _B4AActivationSeed(
    'Tibial raise na parede leve',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial anterior',
    'extensores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'ativar dorsiflexao do tornozelo com apoio na parede',
  ),
  _B4AActivationSeed(
    'Tibial raise na parede leve regressivo',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial anterior',
    'extensores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'reduzir amplitude no tibial raise mantendo calcanhar apoiado',
  ),
  _B4AActivationSeed(
    'Tibial raise na parede leve com pausa curta',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial anterior',
    'extensores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'pausar a dorsiflexao no tibial raise sem compensar com anca',
  ),
  _B4AActivationSeed(
    'Tibial raise na parede leve em ritmo lento',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial anterior',
    'extensores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'controlar subida e descida dos dedos no tibial raise',
  ),
  _B4AActivationSeed(
    'Short foot controlado',
    'tornozelo e pe',
    _ankleEquipment,
    'musculos intrinsecos do pe',
    'tibial posterior; flexores dos dedos; estabilizadores do arco plantar',
    'pe; tornozelo',
    'ativar arco plantar sem enrolar os dedos',
  ),
  _B4AActivationSeed(
    'Short foot controlado regressivo',
    'tornozelo e pe',
    _ankleEquipment,
    'musculos intrinsecos do pe',
    'tibial posterior; flexores dos dedos; estabilizadores do arco plantar',
    'pe; tornozelo',
    'praticar short foot sentado antes de passar para pe',
  ),
  _B4AActivationSeed(
    'Short foot controlado com pausa curta',
    'tornozelo e pe',
    _ankleEquipment,
    'musculos intrinsecos do pe',
    'tibial posterior; flexores dos dedos; estabilizadores do arco plantar',
    'pe; tornozelo',
    'pausar a formacao do arco plantar sem prender os dedos',
  ),
  _B4AActivationSeed(
    'Short foot controlado em ritmo lento',
    'tornozelo e pe',
    _ankleEquipment,
    'musculos intrinsecos do pe',
    'tibial posterior; flexores dos dedos; estabilizadores do arco plantar',
    'pe; tornozelo',
    'controlar ativacao e relaxamento do arco plantar',
  ),
  _B4AActivationSeed(
    'Elevacao de calcanhar isometrica baixa',
    'tornozelo e pe',
    _ankleEquipment,
    'gemeos e soleo',
    'tibial posterior; intrinsecos do pe; core leve',
    'tornozelo; pe; joelho',
    'ativar flexao plantar com elevacao baixa e controlada',
  ),
  _B4AActivationSeed(
    'Elevacao de calcanhar isometrica baixa regressivo',
    'tornozelo e pe',
    _ankleEquipment,
    'gemeos e soleo',
    'tibial posterior; intrinsecos do pe; core leve',
    'tornozelo; pe; joelho',
    'reduzir altura da elevacao de calcanhar isometrica',
  ),
  _B4AActivationSeed(
    'Elevacao de calcanhar isometrica baixa com pausa curta',
    'tornozelo e pe',
    _ankleEquipment,
    'gemeos e soleo',
    'tibial posterior; intrinsecos do pe; core leve',
    'tornozelo; pe; joelho',
    'pausar a elevacao baixa mantendo tornozelo alinhado',
  ),
  _B4AActivationSeed(
    'Elevacao de calcanhar isometrica baixa em ritmo lento',
    'tornozelo e pe',
    _ankleEquipment,
    'gemeos e soleo',
    'tibial posterior; intrinsecos do pe; core leve',
    'tornozelo; pe; joelho',
    'subir e descer devagar na elevacao baixa de calcanhar',
  ),
  _B4AActivationSeed(
    'Inversao de tornozelo com elastico leve',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial posterior',
    'tibial anterior; flexores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'ativar inversores do tornozelo com elastico leve',
  ),
  _B4AActivationSeed(
    'Inversao de tornozelo com elastico leve regressivo',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial posterior',
    'tibial anterior; flexores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'reduzir tensao do elastico na inversao de tornozelo',
  ),
  _B4AActivationSeed(
    'Inversao de tornozelo com elastico leve com pausa curta',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial posterior',
    'tibial anterior; flexores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'pausar a inversao sem rodar joelho ou anca',
  ),
  _B4AActivationSeed(
    'Inversao de tornozelo com elastico leve em ritmo lento',
    'tornozelo e pe',
    _ankleEquipment,
    'tibial posterior',
    'tibial anterior; flexores dos dedos; estabilizadores do tornozelo',
    'tornozelo; pe',
    'controlar ida e volta da inversao com elastico leve',
  ),
];

final v099b4aActivationDomainEntries = _b4aActivationSeeds
    .map(
      (seed) => V100CatalogDomainEntryData(
        source: 'GOOD_V1_B4A',
        section: seed.section,
        conceptId: _stableKey(seed.name),
        name: seed.name,
        contextKey: 'ativacao',
        primaryType: 'ativacao',
        equipment: seed.equipment,
        primaryMuscle: seed.primaryMuscle,
        secondaryMuscles: seed.secondaryMuscles,
        joint: seed.joint,
        goal: seed.goal,
        priority: 'B4A',
        safety: _safety,
      ),
    )
    .toList(growable: false);

String _stableKey(String value) {
  return value
      .toLowerCase()
      .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '');
}
