import 'v100_catalog_domain_data.dart';

const v099b6bMobilityFlexibilityDomainEntries = <V100CatalogDomainEntryData>[
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: '9090hipswitch',
    name: '90-90 hip switch',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: '9090hipswitchregressivo',
    name: '90-90 hip switch regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: '9090hipswitchcompausacurta',
    name: '90-90 hip switch com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: '9090hipswitchemritmolento',
    name: '90-90 hip switch em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'carsdeancaemquatroapoios',
    name: 'CARs de anca em quatro apoios',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'carsdeancaemquatroapoiosregressivo',
    name: 'CARs de anca em quatro apoios regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'carsdeancaemquatroapoioscompausacurta',
    name: 'CARs de anca em quatro apoios com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'carsdeancaemquatroapoiosemritmolento',
    name: 'CARs de anca em quatro apoios em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'mobilidadedeancaemposicaodecorredor',
    name: 'Mobilidade de anca em posicao de corredor',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'mobilidadedeancaemposicaodecorredorregressivo',
    name: 'Mobilidade de anca em posicao de corredor regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'mobilidadedeancaemposicaodecorredorcompausacurta',
    name: 'Mobilidade de anca em posicao de corredor com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'mobilidadedeancaemposicaodecorredoremritmolento',
    name: 'Mobilidade de anca em posicao de corredor em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'rockbackdeadutores',
    name: 'Rockback de adutores',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'rockbackdeadutoresregressivo',
    name: 'Rockback de adutores regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'rockbackdeadutorescompausacurta',
    name: 'Rockback de adutores com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'rockbackdeadutoresemritmolento',
    name: 'Rockback de adutores em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'circulosdeancaempe',
    name: 'Circulos de anca em pe',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'circulosdeancaemperegressivo',
    name: 'Circulos de anca em pe regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'circulosdeancaempecompausacurta',
    name: 'Circulos de anca em pe com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'circulosdeancaempeemritmolento',
    name: 'Circulos de anca em pe em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'aberturadeancanaparede',
    name: 'Abertura de anca na parede',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'anca e membros inferiores',
    conceptId: 'aberturadeancanaparederegressivo',
    name: 'Abertura de anca na parede regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'peso corporal; parede; banco; elastico',
    primaryMuscle: 'mobilidade da anca',
    secondaryMuscles: 'gluteos; adutores; flexores da anca; tornozelo; joelho',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'aumentar amplitude controlada para agachar, correr e pontapear',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'wallslidecomantebracos',
    name: 'Wall slide com antebracos',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'wallslidecomantebracosregressivo',
    name: 'Wall slide com antebracos regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'wallslidecomantebracoscompausacurta',
    name: 'Wall slide com antebracos com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'wallslidecomantebracosemritmolento',
    name: 'Wall slide com antebracos em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'passthroughcompau',
    name: 'Pass-through com pau',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'passthroughcompauregressivo',
    name: 'Pass-through com pau regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'passthroughcompaucompausacurta',
    name: 'Pass-through com pau com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'passthroughcompauemritmolento',
    name: 'Pass-through com pau em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'carsdeombroempe',
    name: 'CARs de ombro em pe',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'carsdeombroemperegressivo',
    name: 'CARs de ombro em pe regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'carsdeombroempecompausacurta',
    name: 'CARs de ombro em pe com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'carsdeombroempeemritmolento',
    name: 'CARs de ombro em pe em ritmo lento',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'rotacaoexternanaparede',
    name: 'Rotacao externa na parede',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'rotacaoexternanaparederegressivo',
    name: 'Rotacao externa na parede regressivo',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'ombro, coluna e punho',
    conceptId: 'rotacaoexternanaparedecompausacurta',
    name: 'Rotacao externa na parede com pausa curta',
    contextKey: 'mobilidade',
    primaryType: 'mobilidade',
    equipment: 'parede; stick; foamroller; cadeira',
    primaryMuscle: 'mobilidade toracica',
    secondaryMuscles: 'ombro; escapula; lombar; pescoco; punho',
    joint: 'toracica; lombar; cervical; ombro; punho',
    goal: 'melhorar mobilidade de tronco e membros superiores',
    priority: 'B6B',
    safety:
        'Mantem movimento ativo e controlado, sem forcar amplitude nem procurar dor. Reduz alcance se houver desconforto articular.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeisquiotibiaiscomstrap',
    name: 'Alongamento de isquiotibiais com strap',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeisquiotibiaiscomstrapregressivo',
    name: 'Alongamento de isquiotibiais com strap regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeisquiotibiaiscomstrapcompausacurta',
    name: 'Alongamento de isquiotibiais com strap com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeisquiotibiaiscomstrapemritmolento',
    name: 'Alongamento de isquiotibiais com strap em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeposteriorsentado',
    name: 'Alongamento de posterior sentado',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeposteriorsentadoregressivo',
    name: 'Alongamento de posterior sentado regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeposteriorsentadocompausacurta',
    name: 'Alongamento de posterior sentado com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodeposteriorsentadoemritmolento',
    name: 'Alongamento de posterior sentado em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodegemeosnaparede',
    name: 'Alongamento de gemeos na parede',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodegemeosnaparederegressivo',
    name: 'Alongamento de gemeos na parede regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodegemeosnaparedecompausacurta',
    name: 'Alongamento de gemeos na parede com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodegemeosnaparedeemritmolento',
    name: 'Alongamento de gemeos na parede em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodesoleonaparede',
    name: 'Alongamento de soleo na parede',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodesoleonaparederegressivo',
    name: 'Alongamento de soleo na parede regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodesoleonaparedecompausacurta',
    name: 'Alongamento de soleo na parede com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodesoleonaparedeemritmolento',
    name: 'Alongamento de soleo na parede em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodecadeiaposteriordeitado',
    name: 'Alongamento de cadeia posterior deitado',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodecadeiaposteriordeitadoregressivo',
    name: 'Alongamento de cadeia posterior deitado regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodecadeiaposteriordeitadocompausacurta',
    name: 'Alongamento de cadeia posterior deitado com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'cadeia posterior e anca',
    conceptId: 'alongamentodecadeiaposteriordeitadoemritmolento',
    name: 'Alongamento de cadeia posterior deitado em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'strap; parede; almofada; peso corporal',
    primaryMuscle: 'isquiotibiais',
    secondaryMuscles: 'gemeos; gluteos; flexores da anca; adutores; lombar',
    joint: 'anca; joelho; tornozelo; lombar',
    goal: 'alongar cadeia posterior e anca com respiracao e sem dor',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodepeitoralnaporta',
    name: 'Alongamento de peitoral na porta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodepeitoralnaportaregressivo',
    name: 'Alongamento de peitoral na porta regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodepeitoralnaportacompausacurta',
    name: 'Alongamento de peitoral na porta com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodepeitoralnaportaemritmolento',
    name: 'Alongamento de peitoral na porta em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodedorsalnaparede',
    name: 'Alongamento de dorsal na parede',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodedorsalnaparederegressivo',
    name: 'Alongamento de dorsal na parede regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodedorsalnaparedecompausacurta',
    name: 'Alongamento de dorsal na parede com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodedorsalnaparedeemritmolento',
    name: 'Alongamento de dorsal na parede em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodeombrocruzado',
    name: 'Alongamento de ombro cruzado',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodeombrocruzadoregressivo',
    name: 'Alongamento de ombro cruzado regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodeombrocruzadocompausacurta',
    name: 'Alongamento de ombro cruzado com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodeombrocruzadoemritmolento',
    name: 'Alongamento de ombro cruzado em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodetricepsacimadacabeca',
    name: 'Alongamento de triceps acima da cabeca',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodetricepsacimadacabecaregressivo',
    name: 'Alongamento de triceps acima da cabeca regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodetricepsacimadacabecacompausacurta',
    name: 'Alongamento de triceps acima da cabeca com pausa curta',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodetricepsacimadacabecaemritmolento',
    name: 'Alongamento de triceps acima da cabeca em ritmo lento',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodebicepsnaparede',
    name: 'Alongamento de biceps na parede',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6B',
    section: 'tronco e membros superiores',
    conceptId: 'alongamentodebicepsnaparederegressivo',
    name: 'Alongamento de biceps na parede regressivo',
    contextKey: 'elasticidade',
    primaryType: 'elasticidade',
    equipment: 'parede; porta; toalha',
    primaryMuscle: 'peitoral maior',
    secondaryMuscles: 'dorsais; ombros; antebracos; pescoco; triceps',
    joint: 'ombro; cotovelo; punho; cervical',
    goal: 'alongar zonas que limitam empurrar, puxar e postura',
    priority: 'B6B',
    safety:
        'Mantem alongamento confortavel e respiracao calma, sem ressalto nem dor. Sai da posicao se houver formigueiro, tontura ou dor aguda.',
  ),
];
