import 'v100_catalog_domain_data.dart';

class _B3StrengthSeed {
  const _B3StrengthSeed(
    this.name,
    this.section,
    this.contextKey,
    this.equipment,
    this.primaryMuscle,
    this.secondaryMuscles,
    this.joint,
    this.goal, [
    this.source = 'GOOD_V1_B3',
  ]);

  final String name;
  final String section;
  final String contextKey;
  final String equipment;
  final String primaryMuscle;
  final String secondaryMuscles;
  final String joint;
  final String goal;
  final String source;
}

const _safety =
    'Carga progressiva, amplitude confortavel e paragem imediata se houver dor aguda ou perda de tecnica.';

const _b3StrengthSeeds = <_B3StrengthSeed>[
  _B3StrengthSeed(
    'Supino inclinado com barra',
    'peito',
    'peito',
    'Barra e banco inclinado',
    'peitoral maior',
    'triceps; deltoide anterior; serratil anterior',
    'ombro; cotovelo; escapula',
    'treinar empurrar inclinado com barra',
  ),
  _B3StrengthSeed(
    'Supino declinado com barra',
    'peito',
    'peito',
    'Barra e banco declinado',
    'peitoral maior',
    'triceps; deltoide anterior; serratil anterior',
    'ombro; cotovelo; escapula',
    'treinar empurrar declinado com barra',
  ),
  _B3StrengthSeed(
    'Supino inclinado com halteres',
    'peito',
    'peito',
    'Halteres e banco inclinado',
    'peitoral maior',
    'triceps; deltoide anterior; serratil anterior',
    'ombro; cotovelo; escapula',
    'treinar empurrar inclinado com halteres',
  ),
  _B3StrengthSeed(
    'Press militar com barra',
    'ombros',
    'ombros',
    'Barra',
    'deltoides',
    'triceps; trapezio superior; core',
    'ombro; cotovelo; escapula',
    'treinar empurrar vertical com barra',
  ),
  _B3StrengthSeed(
    'Press de ombro na maquina',
    'ombros',
    'ombros',
    'Maquina de ombro',
    'deltoides',
    'triceps; trapezio superior',
    'ombro; cotovelo; escapula',
    'treinar empurrar vertical guiado',
  ),
  _B3StrengthSeed(
    'Press de ombro na maquina controlado',
    'ombros',
    'ombros',
    'Maquina de ombro',
    'deltoides',
    'triceps; trapezio superior',
    'ombro; cotovelo; escapula',
    'controlar empurrar vertical guiado',
  ),
  _B3StrengthSeed(
    'Press de ombro na maquina com pausa',
    'ombros',
    'ombros',
    'Maquina de ombro',
    'deltoides',
    'triceps; trapezio superior',
    'ombro; cotovelo; escapula',
    'pausar o press guiado sem perder postura',
  ),
  _B3StrengthSeed(
    'Press de ombro na maquina em tempo lento',
    'ombros',
    'ombros',
    'Maquina de ombro',
    'deltoides',
    'triceps; trapezio superior',
    'ombro; cotovelo; escapula',
    'aumentar controlo no press guiado',
  ),
  _B3StrengthSeed(
    'Curl martelo',
    'biceps',
    'biceps',
    'Halteres',
    'biceps braquial',
    'braquial; braquiorradial; antebraco',
    'cotovelo; punho',
    'treinar flexao do cotovelo com pegada neutra',
  ),
  _B3StrengthSeed(
    'Curl no cabo baixo',
    'biceps',
    'biceps',
    'Cabo baixo',
    'biceps braquial',
    'braquial; braquiorradial; antebraco',
    'cotovelo; punho; ombro',
    'treinar biceps com tensao continua no cabo',
  ),
  _B3StrengthSeed(
    'Curl no cabo baixo controlado',
    'biceps',
    'biceps',
    'Cabo baixo',
    'biceps braquial',
    'braquial; braquiorradial; antebraco',
    'cotovelo; punho; ombro',
    'controlar curl no cabo baixo sem balanco',
  ),
  _B3StrengthSeed(
    'Curl no cabo baixo com pausa',
    'biceps',
    'biceps',
    'Cabo baixo',
    'biceps braquial',
    'braquial; braquiorradial; antebraco',
    'cotovelo; punho; ombro',
    'pausar o curl no cabo baixo com cotovelos estaveis',
  ),
  _B3StrengthSeed(
    'Curl no cabo baixo em tempo lento',
    'biceps',
    'biceps',
    'Cabo baixo',
    'biceps braquial',
    'braquial; braquiorradial; antebraco',
    'cotovelo; punho; ombro',
    'aumentar controlo no curl no cabo baixo',
  ),
  _B3StrengthSeed(
    'Static hold com halteres',
    'antebraco_pegada',
    'antebraco_pega',
    'Halteres',
    'flexores do antebraco',
    'trapezio; core; dedos',
    'punho; cotovelo; ombro',
    'treinar resistencia de pegada em posicao estatica',
  ),
  _B3StrengthSeed(
    'Static hold com halteres regressivo',
    'antebraco_pegada',
    'antebraco_pega',
    'Halteres',
    'flexores do antebraco',
    'trapezio; core; dedos',
    'punho; cotovelo; ombro',
    'reduzir carga no static hold mantendo pegada limpa',
  ),
  _B3StrengthSeed(
    'Static hold com halteres com pausa curta',
    'antebraco_pegada',
    'antebraco_pega',
    'Halteres',
    'flexores do antebraco',
    'trapezio; core; dedos',
    'punho; cotovelo; ombro',
    'pausar static hold com postura alta',
  ),
  _B3StrengthSeed(
    'Static hold com halteres em ritmo lento',
    'antebraco_pegada',
    'antebraco_pega',
    'Halteres',
    'flexores do antebraco',
    'trapezio; core; dedos',
    'punho; cotovelo; ombro',
    'prolongar static hold sem perder ombros',
  ),
  _B3StrengthSeed(
    'Pallof press no cabo',
    'core',
    'core',
    'Cabo baixo',
    'core anterior',
    'obliquos; transverso abdominal; gluteos',
    'coluna; anca; ombro',
    'treinar anti-rotacao com tensao do cabo',
  ),
  _B3StrengthSeed(
    'Dead bug com medicine ball',
    'core',
    'core',
    'Bola medicinal e tapete',
    'core anterior',
    'transverso abdominal; flexores da anca; ombros',
    'coluna; anca; ombro',
    'controlar dead bug segurando bola medicinal leve',
  ),
  _B3StrengthSeed(
    'Hip thrust com barra em tempo lento',
    'gluteos',
    'gluteos',
    'Barra e banco',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core; quadriceps',
    'anca; joelho; coluna',
    'aumentar controlo no hip thrust com barra',
  ),
  _B3StrengthSeed(
    'Hip thrust na Smith machine',
    'gluteos',
    'gluteos',
    'Smith machine e banco',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core; quadriceps',
    'anca; joelho; coluna',
    'treinar extensao da anca guiada na Smith machine',
  ),
  _B3StrengthSeed(
    'Hip thrust na Smith machine controlado',
    'gluteos',
    'gluteos',
    'Smith machine e banco',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core; quadriceps',
    'anca; joelho; coluna',
    'controlar hip thrust guiado sem arquear lombar',
  ),
  _B3StrengthSeed(
    'Hip thrust na Smith machine com pausa',
    'gluteos',
    'gluteos',
    'Smith machine e banco',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core; quadriceps',
    'anca; joelho; coluna',
    'pausar no topo do hip thrust na Smith machine',
  ),
  _B3StrengthSeed(
    'Hip thrust na Smith machine em tempo lento',
    'gluteos',
    'gluteos',
    'Smith machine e banco',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core; quadriceps',
    'anca; joelho; coluna',
    'aumentar controlo no hip thrust guiado',
  ),
  _B3StrengthSeed(
    'Glute bridge com barra',
    'gluteos',
    'gluteos',
    'Barra e tapete',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; joelho; coluna',
    'treinar extensao da anca a partir do chao',
  ),
  _B3StrengthSeed(
    'Glute bridge com barra controlado',
    'gluteos',
    'gluteos',
    'Barra e tapete',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; joelho; coluna',
    'controlar glute bridge com barra sem compensar lombar',
  ),
  _B3StrengthSeed(
    'Glute bridge com barra com pausa',
    'gluteos',
    'gluteos',
    'Barra e tapete',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; joelho; coluna',
    'pausar glute bridge no topo com costelas baixas',
  ),
  _B3StrengthSeed(
    'Glute bridge com barra em tempo lento',
    'gluteos',
    'gluteos',
    'Barra e tapete',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; joelho; coluna',
    'aumentar controlo no glute bridge com barra',
  ),
  _B3StrengthSeed(
    'Kickback de gluteo no cabo',
    'gluteos',
    'gluteos',
    'Cabo baixo e tornozeleira',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; coluna',
    'treinar extensao da anca no cabo sem balanco',
  ),
  _B3StrengthSeed(
    'Kickback de gluteo no cabo controlado',
    'gluteos',
    'gluteos',
    'Cabo baixo e tornozeleira',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; coluna',
    'controlar kickback no cabo com pelvis estavel',
  ),
  _B3StrengthSeed(
    'Kickback de gluteo no cabo com pausa',
    'gluteos',
    'gluteos',
    'Cabo baixo e tornozeleira',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; coluna',
    'pausar kickback no cabo no fim da extensao',
  ),
  _B3StrengthSeed(
    'Kickback de gluteo no cabo em tempo lento',
    'gluteos',
    'gluteos',
    'Cabo baixo e tornozeleira',
    'gluteo maximo',
    'gluteo medio; isquiotibiais; core',
    'anca; coluna',
    'aumentar controlo no kickback no cabo',
  ),
  _B3StrengthSeed(
    'Leg press unilateral',
    'quadriceps',
    'pernas',
    'Leg press',
    'quadriceps e gluteos',
    'isquiotibiais; adutores; gemeos',
    'joelho; anca',
    'treinar empurrar unilateral no leg press',
  ),
  _B3StrengthSeed(
    'Leg press unilateral controlado',
    'quadriceps',
    'pernas',
    'Leg press',
    'quadriceps e gluteos',
    'isquiotibiais; adutores; gemeos',
    'joelho; anca',
    'controlar leg press unilateral com joelho alinhado',
  ),
  _B3StrengthSeed(
    'Leg press unilateral com pausa',
    'quadriceps',
    'pernas',
    'Leg press',
    'quadriceps e gluteos',
    'isquiotibiais; adutores; gemeos',
    'joelho; anca',
    'pausar leg press unilateral em amplitude segura',
  ),
  _B3StrengthSeed(
    'Leg press unilateral em tempo lento',
    'quadriceps',
    'pernas',
    'Leg press',
    'quadriceps e gluteos',
    'isquiotibiais; adutores; gemeos',
    'joelho; anca',
    'aumentar controlo no leg press unilateral',
  ),
  _B3StrengthSeed(
    'Leg curl unilateral',
    'isquiotibiais',
    'pernas',
    'Leg curl',
    'isquiotibiais',
    'gemeos; core leve',
    'joelho',
    'treinar flexao do joelho unilateral',
  ),
  _B3StrengthSeed(
    'Leg curl unilateral controlado',
    'isquiotibiais',
    'pernas',
    'Leg curl',
    'isquiotibiais',
    'gemeos; core leve',
    'joelho',
    'controlar leg curl unilateral sem levantar anca',
  ),
  _B3StrengthSeed(
    'Leg curl unilateral com pausa',
    'isquiotibiais',
    'pernas',
    'Leg curl',
    'isquiotibiais',
    'gemeos; core leve',
    'joelho',
    'pausar leg curl unilateral com joelho estavel',
  ),
  _B3StrengthSeed(
    'Leg curl unilateral em tempo lento',
    'isquiotibiais',
    'pernas',
    'Leg curl',
    'isquiotibiais',
    'gemeos; core leve',
    'joelho',
    'aumentar controlo no leg curl unilateral',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com barra',
    'isquiotibiais',
    'pernas',
    'Barra',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'treinar hinge de anca com barra',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com barra controlado',
    'isquiotibiais',
    'pernas',
    'Barra',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'controlar hinge com barra sem arredondar lombar',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com barra com pausa',
    'isquiotibiais',
    'pernas',
    'Barra',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'pausar peso morto romeno na posicao baixa segura',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com barra em tempo lento',
    'isquiotibiais',
    'pernas',
    'Barra',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'aumentar controlo no peso morto romeno com barra',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com halteres',
    'isquiotibiais',
    'pernas',
    'Halteres',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'treinar hinge de anca com halteres',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com halteres controlado',
    'isquiotibiais',
    'pernas',
    'Halteres',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'controlar hinge com halteres sem perder coluna neutra',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com halteres com pausa',
    'isquiotibiais',
    'pernas',
    'Halteres',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'pausar peso morto romeno com halteres no fundo seguro',
  ),
  _B3StrengthSeed(
    'Peso morto romeno com halteres em tempo lento',
    'isquiotibiais',
    'pernas',
    'Halteres',
    'isquiotibiais e gluteos',
    'lombar; adutores; dorsais estabilizadores',
    'anca; joelho; coluna',
    'aumentar controlo no peso morto romeno com halteres',
  ),
  _B3StrengthSeed(
    'Maquina adutora',
    'adutores',
    'pernas',
    'Maquina adutora',
    'adutores da anca',
    'core leve; gluteos estabilizadores',
    'anca',
    'treinar aducao da anca guiada',
  ),
  _B3StrengthSeed(
    'Maquina adutora regressivo',
    'adutores',
    'pernas',
    'Maquina adutora',
    'adutores da anca',
    'core leve; gluteos estabilizadores',
    'anca',
    'reduzir amplitude na maquina adutora mantendo controlo',
  ),
  _B3StrengthSeed(
    'Maquina adutora com pausa curta',
    'adutores',
    'pernas',
    'Maquina adutora',
    'adutores da anca',
    'core leve; gluteos estabilizadores',
    'anca',
    'pausar a aducao guiada sem forca maxima',
  ),
  _B3StrengthSeed(
    'Maquina adutora em ritmo lento',
    'adutores',
    'pernas',
    'Maquina adutora',
    'adutores da anca',
    'core leve; gluteos estabilizadores',
    'anca',
    'aumentar controlo na maquina adutora',
  ),
  _B3StrengthSeed(
    'Aducao de anca no cabo',
    'adutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'adutores da anca',
    'core; gluteos estabilizadores',
    'anca',
    'treinar aducao da anca no cabo',
  ),
  _B3StrengthSeed(
    'Aducao de anca no cabo regressivo',
    'adutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'adutores da anca',
    'core; gluteos estabilizadores',
    'anca',
    'reduzir amplitude na aducao de anca no cabo',
  ),
  _B3StrengthSeed(
    'Aducao de anca no cabo com pausa curta',
    'adutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'adutores da anca',
    'core; gluteos estabilizadores',
    'anca',
    'pausar aducao de anca no cabo com pelvis estavel',
  ),
  _B3StrengthSeed(
    'Aducao de anca no cabo em ritmo lento',
    'adutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'adutores da anca',
    'core; gluteos estabilizadores',
    'anca',
    'aumentar controlo na aducao de anca no cabo',
  ),
  _B3StrengthSeed(
    'Maquina abdutora',
    'abdutores',
    'pernas',
    'Maquina abdutora',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core leve',
    'anca',
    'treinar abducao da anca guiada',
  ),
  _B3StrengthSeed(
    'Maquina abdutora regressivo',
    'abdutores',
    'pernas',
    'Maquina abdutora',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core leve',
    'anca',
    'reduzir amplitude na maquina abdutora mantendo controlo',
  ),
  _B3StrengthSeed(
    'Maquina abdutora com pausa curta',
    'abdutores',
    'pernas',
    'Maquina abdutora',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core leve',
    'anca',
    'pausar abducao guiada com pelvis estavel',
  ),
  _B3StrengthSeed(
    'Maquina abdutora em ritmo lento',
    'abdutores',
    'pernas',
    'Maquina abdutora',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core leve',
    'anca',
    'aumentar controlo na maquina abdutora',
  ),
  _B3StrengthSeed(
    'Abducao de anca no cabo',
    'abdutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core',
    'anca',
    'treinar abducao da anca no cabo',
  ),
  _B3StrengthSeed(
    'Abducao de anca no cabo regressivo',
    'abdutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core',
    'anca',
    'reduzir amplitude na abducao de anca no cabo',
  ),
  _B3StrengthSeed(
    'Abducao de anca no cabo com pausa curta',
    'abdutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core',
    'anca',
    'pausar abducao de anca no cabo com pelvis estavel',
  ),
  _B3StrengthSeed(
    'Abducao de anca no cabo em ritmo lento',
    'abdutores',
    'pernas',
    'Cabo baixo e tornozeleira',
    'abdutores da anca',
    'gluteo medio; gluteo minimo; core',
    'anca',
    'aumentar controlo na abducao de anca no cabo',
  ),
  _B3StrengthSeed(
    'Hack squat na maquina',
    'quadriceps',
    'pernas',
    'Maquina hack squat',
    'quadriceps e gluteos',
    'adutores; isquiotibiais; gemeos; core',
    'joelho; anca; tornozelo',
    'treinar agachamento guiado com enfase em quadriceps',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Agachamento frontal com barra',
    'quadriceps',
    'pernas',
    'Barra',
    'quadriceps e gluteos',
    'core; adutores; eretores da coluna; gemeos',
    'joelho; anca; coluna; tornozelo',
    'treinar agachamento com tronco vertical e barra anterior',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Remo Meadows com barra',
    'costas',
    'costas',
    'Barra apoiada no canto',
    'costas medias e dorsais',
    'romboides; trapezio medio; biceps; core anti-rotacao',
    'ombro; cotovelo; escapula; coluna',
    'treinar remada unilateral pesada com barra apoiada',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Pullover no cabo em pe',
    'costas',
    'costas',
    'Cabo alto',
    'grande dorsal',
    'serrati anterior; triceps longo; core',
    'ombro; escapula; coluna',
    'treinar extensao do ombro para dorsais sem flexao do cotovelo',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Elevacao lateral na maquina',
    'ombros',
    'ombros',
    'Maquina de elevacao lateral',
    'deltoide medio',
    'deltoide anterior; trapezio superior; core leve',
    'ombro; escapula',
    'treinar abducao do ombro guiada com amplitude controlada',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Crucifixo inverso com halteres no banco inclinado',
    'ombros',
    'ombros',
    'Halteres e banco inclinado',
    'deltoide posterior',
    'romboides; trapezio medio; rotadores externos',
    'ombro; escapula',
    'treinar deltoide posterior com apoio no banco inclinado',
    'GOOD_V1_ADDENDUM',
  ),
  _B3StrengthSeed(
    'Extensao de triceps na corda acima da cabeca',
    'triceps',
    'triceps',
    'Cabo alto e corda',
    'triceps braquial',
    'core; deltoide anterior; serratil anterior',
    'cotovelo; ombro; escapula',
    'treinar extensao do cotovelo acima da cabeca com cabo',
    'GOOD_V1_ADDENDUM',
  ),
];

final v099b3StrengthDomainEntries = _b3StrengthSeeds
    .map(
      (seed) => V100CatalogDomainEntryData(
        source: seed.source,
        section: seed.section,
        conceptId: _stableKey(seed.name),
        name: seed.name,
        contextKey: seed.contextKey,
        primaryType: 'musculacao',
        equipment: seed.equipment,
        primaryMuscle: seed.primaryMuscle,
        secondaryMuscles: seed.secondaryMuscles,
        joint: seed.joint,
        goal: seed.goal,
        priority: 'B3',
        safety: _safety,
      ),
    )
    .toList(growable: false);

String _stableKey(String value) {
  var text = value.toLowerCase();
  const replacements = {
    'á': 'a',
    'à': 'a',
    'ã': 'a',
    'â': 'a',
    'é': 'e',
    'ê': 'e',
    'í': 'i',
    'ó': 'o',
    'õ': 'o',
    'ô': 'o',
    'ú': 'u',
    'ç': 'c',
  };
  for (final entry in replacements.entries) {
    text = text.replaceAll(entry.key, entry.value);
  }
  return text
      .replaceAll(RegExp(r'[^a-z0-9]+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '');
}
