import 'v100_catalog_domain_data.dart';

const v099b6aCardioWarmupRecoveryDomainEntries = <V100CatalogDomainEntryData>[
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'caminhada_leve_na_passadeira',
    name: 'Caminhada leve na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada leve na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'caminhada_leve_na_passadeira_com_controlo_de_respiracao',
    name: 'Caminhada leve na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada leve na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'caminhada_inclinada_na_passadeira',
    name: 'Caminhada inclinada na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada inclinada na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'caminhada_inclinada_na_passadeira_com_controlo_de_respiracao',
    name: 'Caminhada inclinada na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada inclinada na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'corrida_leve_na_passadeira',
    name: 'Corrida leve na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida leve na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'corrida_leve_na_passadeira_com_controlo_de_respiracao',
    name: 'Corrida leve na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida leve na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'corrida_moderada_na_passadeira',
    name: 'Corrida moderada na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida moderada na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'corrida_moderada_na_passadeira_com_controlo_de_respiracao',
    name: 'Corrida moderada na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida moderada na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'intervalos_curtos_na_passadeira',
    name: 'Intervalos curtos na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Intervalos curtos na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'intervalos_curtos_na_passadeira_com_controlo_de_respiracao',
    name: 'Intervalos curtos na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Intervalos curtos na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'intervalos_longos_na_passadeira',
    name: 'Intervalos longos na passadeira',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Intervalos longos na passadeira com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'passadeira',
    conceptId: 'intervalos_longos_na_passadeira_com_controlo_de_respiracao',
    name: 'Intervalos longos na passadeira com controlo de respiracao',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Passadeira',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Intervalos longos na passadeira com controlo de respiracao com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'bicicleta_leve_em_cadencia_estavel',
    name: 'Bicicleta leve em cadencia estavel',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Bicicleta leve em cadencia estavel com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'bicicleta_leve_em_cadencia_estavel_progressivo',
    name: 'Bicicleta leve em cadencia estavel progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Bicicleta leve em cadencia estavel progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'bicicleta_intervalada_moderada',
    name: 'Bicicleta intervalada moderada',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Bicicleta intervalada moderada com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'bicicleta_intervalada_moderada_progressivo',
    name: 'Bicicleta intervalada moderada progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Bicicleta intervalada moderada progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'eliptica_leve_continua',
    name: 'Eliptica leve continua',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Eliptica leve continua com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'eliptica_leve_continua_progressivo',
    name: 'Eliptica leve continua progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Eliptica leve continua progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'eliptica_intervalada_suave',
    name: 'Eliptica intervalada suave',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Eliptica intervalada suave com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'eliptica_intervalada_suave_progressivo',
    name: 'Eliptica intervalada suave progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Eliptica intervalada suave progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'caminhada_rapida_exterior',
    name: 'Caminhada rapida exterior',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada rapida exterior com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'caminhada_rapida_exterior_progressivo',
    name: 'Caminhada rapida exterior progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Caminhada rapida exterior progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corrida_leve_exterior',
    name: 'Corrida leve exterior',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida leve exterior com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corrida_leve_exterior_progressivo',
    name: 'Corrida leve exterior progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corrida leve exterior progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'fartlek_iniciante',
    name: 'Fartlek iniciante',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Fartlek iniciante com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'fartlek_iniciante_progressivo',
    name: 'Fartlek iniciante progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Fartlek iniciante progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corda_ritmo_leve',
    name: 'Corda ritmo leve',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corda ritmo leve com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corda_ritmo_leve_progressivo',
    name: 'Corda ritmo leve progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corda ritmo leve progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corda_intervalada_curta',
    name: 'Corda intervalada curta',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corda intervalada curta com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'corda_intervalada_curta_progressivo',
    name: 'Corda intervalada curta progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Corda intervalada curta progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'hiit_baixo_impacto_sem_saltos',
    name: 'HIIT baixo impacto sem saltos',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar HIIT baixo impacto sem saltos com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'hiit_baixo_impacto_sem_saltos_progressivo',
    name: 'HIIT baixo impacto sem saltos progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar HIIT baixo impacto sem saltos progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'marcha_rapida_no_lugar',
    name: 'Marcha rapida no lugar',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Marcha rapida no lugar com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'marcha_rapida_no_lugar_progressivo',
    name: 'Marcha rapida no lugar progressivo',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Marcha rapida no lugar progressivo com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'baixo impacto e exterior',
    conceptId: 'step_jack_baixo_impacto',
    name: 'Step jack baixo impacto',
    contextKey: 'cardio',
    primaryType: 'cardio',
    equipment: 'Bicicleta estatica, eliptica, corda ou peso corporal',
    primaryMuscle: 'sistema cardiovascular',
    secondaryMuscles: 'pernas; core; respiracao; ritmo',
    joint: 'anca; joelho; tornozelo',
    goal:
        'treinar Step jack baixo impacto com intensidade progressiva e respiracao controlada',
    priority: 'B6A',
    safety:
        'Mantem intensidade conversavel quando aplicavel, reduz ritmo se houver tontura, dor no peito ou falta de ar invulgar.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_diafragmatica_deitado',
    name: 'Respiracao diafragmatica deitado',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao diafragmatica deitado para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_diafragmatica_deitado_regressivo',
    name: 'Respiracao diafragmatica deitado regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao diafragmatica deitado regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_diafragmatica_deitado_com_pausa_curta',
    name: 'Respiracao diafragmatica deitado com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao diafragmatica deitado com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_diafragmatica_deitado_em_ritmo_lento',
    name: 'Respiracao diafragmatica deitado em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao diafragmatica deitado em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_4_6_sentado',
    name: 'Respiracao 4-6 sentado',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao 4-6 sentado para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_4_6_sentado_regressivo',
    name: 'Respiracao 4-6 sentado regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao 4-6 sentado regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_4_6_sentado_com_pausa_curta',
    name: 'Respiracao 4-6 sentado com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao 4-6 sentado com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_4_6_sentado_em_ritmo_lento',
    name: 'Respiracao 4-6 sentado em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao 4-6 sentado em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_lateral_nas_costelas',
    name: 'Respiracao lateral nas costelas',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao lateral nas costelas para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_lateral_nas_costelas_regressivo',
    name: 'Respiracao lateral nas costelas regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao lateral nas costelas regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_lateral_nas_costelas_com_pausa_curta',
    name: 'Respiracao lateral nas costelas com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao lateral nas costelas com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'respiracao_lateral_nas_costelas_em_ritmo_lento',
    name: 'Respiracao lateral nas costelas em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Respiracao lateral nas costelas em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'relaxamento_progressivo_pos_treino',
    name: 'Relaxamento progressivo pos-treino',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Relaxamento progressivo pos-treino para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'relaxamento_progressivo_pos_treino_regressivo',
    name: 'Relaxamento progressivo pos-treino regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Relaxamento progressivo pos-treino regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'relaxamento_progressivo_pos_treino_com_pausa_curta',
    name: 'Relaxamento progressivo pos-treino com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Relaxamento progressivo pos-treino com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'respiracao e cooldown',
    conceptId: 'relaxamento_progressivo_pos_treino_em_ritmo_lento',
    name: 'Relaxamento progressivo pos-treino em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Peso corporal, tapete, passadeira ou bicicleta',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Relaxamento progressivo pos-treino em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_quadriceps',
    name: 'Foam roller nos quadriceps',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos quadriceps para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_quadriceps_regressivo',
    name: 'Foam roller nos quadriceps regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos quadriceps regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_quadriceps_com_pausa_curta',
    name: 'Foam roller nos quadriceps com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos quadriceps com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_quadriceps_em_ritmo_lento',
    name: 'Foam roller nos quadriceps em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos quadriceps em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gemeos',
    name: 'Foam roller nos gemeos',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gemeos para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gemeos_regressivo',
    name: 'Foam roller nos gemeos regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gemeos regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gemeos_com_pausa_curta',
    name: 'Foam roller nos gemeos com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gemeos com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gemeos_em_ritmo_lento',
    name: 'Foam roller nos gemeos em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gemeos em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gluteos',
    name: 'Foam roller nos gluteos',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gluteos para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gluteos_regressivo',
    name: 'Foam roller nos gluteos regressivo',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gluteos regressivo para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gluteos_com_pausa_curta',
    name: 'Foam roller nos gluteos com pausa curta',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gluteos com pausa curta para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'foam roller e bola',
    conceptId: 'foam_roller_nos_gluteos_em_ritmo_lento',
    name: 'Foam roller nos gluteos em ritmo lento',
    contextKey: 'recuperacao',
    primaryType: 'recuperacao',
    equipment: 'Foam roller ou bola de massagem',
    primaryMuscle: 'recuperacao ativa',
    secondaryMuscles: 'respiracao; mobilidade leve; relaxamento muscular',
    joint: 'coluna; anca; ombro; joelho; tornozelo',
    goal:
        'usar Foam roller nos gluteos em ritmo lento para baixar intensidade e recuperar sem esforco excessivo',
    priority: 'B6A',
    safety:
        'Usa pressao leve e respiracao calma. Evita zonas dolorosas, dormencia ou pressao direta em articulacoes sensiveis.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'aquecimento_corpo_inteiro_de_5_minutos',
    name: 'Aquecimento corpo inteiro de 5 minutos',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento corpo inteiro de 5 minutos antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'aquecimento_corpo_inteiro_de_5_minutos_progressivo',
    name: 'Aquecimento corpo inteiro de 5 minutos progressivo',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento corpo inteiro de 5 minutos progressivo antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'marcha_ativa_com_mobilidade_de_bracos',
    name: 'Marcha ativa com mobilidade de bracos',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Marcha ativa com mobilidade de bracos antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'marcha_ativa_com_mobilidade_de_bracos_progressivo',
    name: 'Marcha ativa com mobilidade de bracos progressivo',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Marcha ativa com mobilidade de bracos progressivo antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'sequencia_dinamica_de_agachar_e_alcancar',
    name: 'Sequencia dinamica de agachar e alcancar',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Sequencia dinamica de agachar e alcancar antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'sequencia_dinamica_de_agachar_e_alcancar_progressivo',
    name: 'Sequencia dinamica de agachar e alcancar progressivo',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Sequencia dinamica de agachar e alcancar progressivo antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'mobilidade_dinamica_de_corpo_inteiro',
    name: 'Mobilidade dinamica de corpo inteiro',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Mobilidade dinamica de corpo inteiro antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'mobilidade_dinamica_de_corpo_inteiro_progressivo',
    name: 'Mobilidade dinamica de corpo inteiro progressivo',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Mobilidade dinamica de corpo inteiro progressivo antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'aquecimento_articular_da_cabeca_aos_pes',
    name: 'Aquecimento articular da cabeca aos pes',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento articular da cabeca aos pes antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'geral e musculacao',
    conceptId: 'aquecimento_articular_da_cabeca_aos_pes_progressivo',
    name: 'Aquecimento articular da cabeca aos pes progressivo',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento articular da cabeca aos pes progressivo antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_corrida_leve',
    name: 'Aquecimento antes de corrida leve',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de corrida leve antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_corrida_leve_com_baixa_intensidade',
    name: 'Aquecimento antes de corrida leve com baixa intensidade',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de corrida leve com baixa intensidade antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_bicicleta',
    name: 'Aquecimento antes de bicicleta',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de bicicleta antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_bicicleta_com_baixa_intensidade',
    name: 'Aquecimento antes de bicicleta com baixa intensidade',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de bicicleta com baixa intensidade antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_karate',
    name: 'Aquecimento antes de Karate',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de Karate antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_karate_com_baixa_intensidade',
    name: 'Aquecimento antes de Karate com baixa intensidade',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de Karate com baixa intensidade antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_bjj',
    name: 'Aquecimento antes de BJJ',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de BJJ antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_antes_de_bjj_com_baixa_intensidade',
    name: 'Aquecimento antes de BJJ com baixa intensidade',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento antes de BJJ com baixa intensidade antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
  V100CatalogDomainEntryData(
    source: 'GOOD_V1_B6A',
    section: 'cardio e artes marciais',
    conceptId: 'aquecimento_de_punhos_e_ombros_para_tatami',
    name: 'Aquecimento de punhos e ombros para tatami',
    contextKey: 'aquecimento',
    primaryType: 'aquecimento',
    equipment: 'Peso corporal, elastico ou corda leve',
    primaryMuscle: 'preparacao geral',
    secondaryMuscles: 'articulacoes; core; pernas; ombros',
    joint: 'anca; joelho; tornozelo; ombro; coluna',
    goal:
        'preparar o corpo com Aquecimento de punhos e ombros para tatami antes da sessao principal',
    priority: 'B6A',
    safety:
        'Deve preparar sem cansar. Mantem movimentos leves e para se surgir dor aguda ou tontura.',
  ),
];
